# Generated by Django 4.1.6 on 2023-03-29 09:31

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=70)),
                ('complemento', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=120, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('status', models.CharField(choices=[('1', 'ATIVO'), ('2', 'DESATIVADO')], default='1', max_length=2, verbose_name='Status')),
                ('cns', models.PositiveIntegerField(help_text='Digite o cartão do SUS com 15 digitos.', unique=True, verbose_name='Cartão do SUS')),
                ('cargo', models.CharField(choices=[('', '-----------'), ('1', '1-ACS'), ('2', '2-COORDENADOR(A)'), ('3', '3-DIGITADOR'), ('4', '4-ENFERMEIRO'), ('5', '5-FAXINEIRO'), ('6', '6-MÉDICO'), ('7', '7-MOTORISTA'), ('8', '8-RECEPCIONISTA'), ('9', '9-TEC.ENFERMAGEM'), ('10', '10-Outros')], default='', max_length=2, verbose_name='Cargo:')),
                ('sexo', models.CharField(choices=[('', '-----------'), ('F', 'FEMININO'), ('M', 'MASCULINO')], default='', max_length=1, verbose_name='Sexo')),
                ('dt_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profissionais.endereco')),
            ],
        ),
    ]
