# Generated by Django 4.2.7 on 2025-07-16 09:33

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidadao', '0003_alter_endereco_localizacao'),
        ('estabelecimentos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=120, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('status', models.CharField(choices=[('1', 'ATIVO'), ('2', 'DESATIVADO')], default='1', max_length=2, verbose_name='Status')),
                ('cns', models.PositiveBigIntegerField(help_text='Digite o cartão do SUS com 15 digitos.', unique=True, verbose_name='CNS')),
                ('cargo', models.CharField(choices=[('1', 'ACS'), ('2', 'COORDENADOR(A)'), ('3', 'DIGITADOR'), ('4', 'ENFERMEIRO'), ('5', 'FAXINEIRO'), ('6', 'MÉDICO'), ('7', 'MOTORISTA'), ('8', 'RECEPCIONISTA'), ('9', 'SECRETARIO'), ('10', 'TEC.ENFERMAGEM'), ('11', 'DENTISTA'), ('12', 'Outros')], default='', max_length=2, verbose_name='Cargo:')),
                ('sexo', models.CharField(choices=[('', '-----------'), ('F', 'FEMININO'), ('M', 'MASCULINO')], default='', max_length=1, verbose_name='Sexo')),
                ('dt_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidadao.endereco', verbose_name='Endereço')),
                ('estabelecimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profissional_estabelecimento', to='estabelecimentos.estabelecimento', verbose_name='Estabelecimento')),
            ],
        ),
    ]
