# Generated by Django 4.1.6 on 2023-03-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0001_initial'),
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='estabelecimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estabelecimentos.estabelecimento', verbose_name='profissional_estabelecimento'),
        ),
    ]
