# Generated by Django 4.2.7 on 2025-07-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='endereco',
        ),
    ]
