# Generated by Django 4.2.1 on 2023-10-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='endereco',
        ),
    ]
