# Generated by Django 5.2.5 on 2025-08-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_remove_profissional_endereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'ordering': ['nome_completo']},
        ),
    ]
