# Generated by Django 4.2.1 on 2023-10-22 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_remove_profissional_endereco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
