# Generated by Django 4.1.6 on 2023-03-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0003_profissional_microarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.endereco'),
        ),
    ]
