# Generated by Django 4.2.7 on 2023-12-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0003_delete_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='cargo',
            field=models.CharField(choices=[('1', 'ACS'), ('2', 'COORDENADOR(A)'), ('3', 'DIGITADOR'), ('4', 'ENFERMEIRO'), ('5', 'FAXINEIRO'), ('6', 'MÉDICO'), ('7', 'MOTORISTA'), ('8', 'RECEPCIONISTA'), ('9', 'SECRETARIO'), ('10', 'TEC.ENFERMAGEM'), ('11', 'DENTISTA'), ('12', 'Outros')], default='', max_length=2, verbose_name='Cargo:'),
        ),
    ]
