# Generated by Django 4.2.1 on 2023-06-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0003_alter_profissional_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'ATIVO'), ('2', 'DESATIVADO')], default='1', max_length=2, null=True, verbose_name='Status'),
        ),
    ]
