# Generated by Django 4.1.6 on 2023-03-29 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0004_alter_profissional_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='estabelecimento',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='microarea',
        ),
        migrations.AlterField(
            model_name='profissional',
            name='endereco',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='profissionais.endereco', verbose_name='Micro área'),
        ),
    ]
