# Generated by Django 4.2.7 on 2025-06-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0004_alter_profissional_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='microarea',
        ),
    ]
