# Generated by Django 4.2.7 on 2025-06-21 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0004_alter_cidadao_cpf'),
        ('profissionais', '0005_remove_profissional_microarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidadao.endereco', verbose_name='Endereço'),
        ),
    ]
