# Generated by Django 4.1.6 on 2023-03-29 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0002_microarea_estabelecimento'),
        ('profissionais', '0005_remove_profissional_estabelecimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='estabelecimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estabelecimentos.estabelecimento', verbose_name='Estabelecimento'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='microarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estabelecimentos.microarea', verbose_name='Micro área'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.endereco'),
        ),
    ]
