# Generated by Django 4.1.6 on 2023-04-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0003_alter_microarea_microarea'),
        ('profissionais', '0007_alter_profissional_microarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='estabelecimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profissional', to='estabelecimentos.estabelecimento', verbose_name='Estabelecimento'),
        ),
    ]
