# Generated by Django 4.1.6 on 2023-04-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0003_alter_microarea_microarea'),
        ('profissionais', '0010_alter_profissional_estabelecimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='microarea',
            field=models.ForeignKey(blank=True, help_text='Campo somente para ACS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profissional_microarea', to='estabelecimentos.microarea', verbose_name='Micro área'),
        ),
    ]
