# Generated by Django 4.1.6 on 2023-04-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0013_alter_profissional_cns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='cns',
            field=models.PositiveBigIntegerField(help_text='Digite o cartão do SUS com 15 digitos.', unique=True, verbose_name='CNS'),
        ),
    ]
