# Generated by Django 4.2.1 on 2023-05-15 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidadao', '0006_alter_cidadao_cns'),
        ('profissionais', '0014_alter_profissional_cns'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(verbose_name='Data do Pedido')),
                ('classficacao', models.CharField(help_text='TIPO DE URGENCIA', max_length=1, verbose_name='Classificação')),
                ('tipo_consulta', models.CharField(max_length=1, verbose_name='Tipo de Consulta')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='especialidades.tipoespecialidade')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cidadao.cidadao', verbose_name='Paciente')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profissionais.profissional', verbose_name='Profissional')),
            ],
        ),
    ]
