# Generated by Django 4.2.1 on 2023-09-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '0001_initial'),
        ('cidadao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da Especialidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(verbose_name='Data do Pedido')),
                ('classificacao', models.CharField(choices=[('1', 'NORMAL'), ('2', 'URGÊNCIA')], help_text='TIPO DE URGENCIA', max_length=1, verbose_name='Classificação')),
                ('tipo_atendimento', models.CharField(choices=[('1', 'CONSULTA'), ('2', 'RETORNO'), ('3', 'AVALIAÇÃO')], max_length=1, verbose_name='Tipo de Atendimento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('status', models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO')], default=1, max_length=1, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente_especialidades', to='especialidades.especialidade')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidadao.cidadao', verbose_name='Paciente')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profissionais.profissional', verbose_name='Profissional')),
            ],
        ),
        migrations.CreateModel(
            name='AtendimentoEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paciente')),
                ('data', models.DateField(null=True, verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pacientespecialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.pacienteespecialidade')),
            ],
        ),
    ]
