# Generated by Django 5.2.5 on 2025-09-07 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientesia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.pacienteespecialidade', verbose_name='paciente_especialidade_atendimentos'),
        ),
    ]
