# Generated by Django 4.2.7 on 2025-07-16 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteespecialidade',
            name='profissional',
            field=models.ForeignKey(blank=True, help_text='ACS', null=True, on_delete=django.db.models.deletion.PROTECT, to='profissionais.profissional', verbose_name='ACS'),
        ),
    ]
