# Generated by Django 4.2.1 on 2023-05-23 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_alter_profissional_cargo'),
        ('cidadao', '0001_initial'),
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(verbose_name='Data do Pedido')),
                ('classificacao', models.CharField(choices=[('1', 'NORMAL'), ('2', 'URGÊNCIA')], help_text='TIPO DE URGENCIA', max_length=1, verbose_name='Classificação')),
                ('tipo_atendimento', models.CharField(choices=[('1', 'CONSULTA'), ('2', 'RETORNO'), ('3', 'AVALIAÇÃO')], max_length=1, verbose_name='Tipo de Atendimento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('status', models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO')], default=1, max_length=1, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='especialidade',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='especialidade',
            name='data_pedido',
        ),
        migrations.RemoveField(
            model_name='especialidade',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='especialidade',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='especialidade',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='especialidade',
            name='profissional',
        ),
        migrations.RemoveField(
            model_name='especialidade',
            name='status',
        ),
        migrations.RemoveField(
            model_name='especialidade',
            name='tipo_atendimento',
        ),
        migrations.AddField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Nome da Especialidade'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TipoEspecialidade',
        ),
        migrations.AddField(
            model_name='pacienteespecialidade',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipoespecialidade_especialidade', to='especialidades.especialidade'),
        ),
        migrations.AddField(
            model_name='pacienteespecialidade',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidadao.cidadao', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='pacienteespecialidade',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profissionais.profissional', verbose_name='Profissional'),
        ),
    ]
