# Generated by Django 4.2.1 on 2023-05-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidade',
            name='tipo_consulta',
        ),
        migrations.AddField(
            model_name='especialidade',
            name='tipo_atendimento',
            field=models.CharField(default=1, max_length=1, verbose_name='Tipo de Atendimento'),
            preserve_default=False,
        ),
    ]
