# Generated by Django 4.2.7 on 2025-06-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteespecialidade',
            name='classificacao',
            field=models.CharField(choices=[('1', 'ELETIVO'), ('2', 'PRIORIDADE'), ('3', 'URGÊNCIA')], help_text='TIPO DE URGENCIA', max_length=1, verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='pacienteespecialidade',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO'), ('3', 'CANCELADO')], default=1, max_length=1, verbose_name='Status'),
        ),
    ]
