# Generated by Django 4.2.7 on 2025-07-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='atendimento_via',
            field=models.CharField(choices=[('1', 'CIMBAJE'), ('2', 'CEAE'), ('3', 'RECURSO PRÓPRIO'), ('4', 'PPI')], max_length=1, verbose_name=' Atendimento Via'),
        ),
    ]
