# Generated by Django 4.2.1 on 2023-10-22 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0003_delete_endereco'),
        ('especialidades', '0002_alter_atendpaciente_pacientespecialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendpaciente',
            name='pacientespecialidade',
            field=models.CharField(max_length=200, null=True, verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='pacienteespecialidade',
            name='profissional',
            field=models.ForeignKey(help_text='ACS', null=True, on_delete=django.db.models.deletion.PROTECT, to='profissionais.profissional', verbose_name='Profissional'),
        ),
    ]
