# Generated by Django 4.2.1 on 2023-09-18 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0002_alter_atendimentoespecialidade_pacientespecialidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentoespecialidade',
            name='paciente',
        ),
        migrations.AddField(
            model_name='atendimentoespecialidade',
            name='especialidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='especialidades.especialidade'),
        ),
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='pacientespecialidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='especialidades.pacienteespecialidade'),
        ),
    ]
