# Generated by Django 4.2.1 on 2023-05-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0002_remove_especialidade_tipo_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='status',
            field=models.CharField(default=1, max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tipoespecialidade',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome da Especialidade'),
        ),
    ]
