# Generated by Django 4.2.7 on 2025-07-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0002_alter_pacienteespecialidade_profissional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacienteespecialidade',
            name='profissional',
        ),
    ]
