# Generated by Django 4.2.7 on 2025-06-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0002_alter_pacienteespecialidade_classificacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtedimentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.especialidade', verbose_name='Especialidade')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.pacienteespecialidade', verbose_name='Paciente')),
            ],
        ),
    ]
