# Generated by Django 4.2.7 on 2025-06-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0003_atedimentopaciente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AtedimentoPaciente',
            new_name='AtendimentoPaciente',
        ),
    ]
