# Generated by Django 4.2.1 on 2023-05-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0003_especialidade_status_alter_tipoespecialidade_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidade',
            old_name='classficacao',
            new_name='classificacao',
        ),
    ]
