# Generated by Django 4.2.1 on 2023-10-22 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0003_alter_atendpaciente_pacientespecialidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atend_especialidades', to='especialidades.especialidade'),
        ),
        migrations.AlterField(
            model_name='atendpaciente',
            name='Atendespecialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atend_paciente_especialidade', to='especialidades.atendimentoespecialidade'),
        ),
    ]
