# Generated by Django 5.2.5 on 2025-09-08 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0003_alter_pacientesia_paciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacienteespecialidade',
            options={'ordering': ['data_pedido']},
        ),
    ]
