# Generated by Django 4.2.7 on 2025-07-17 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0003_remove_pacienteespecialidade_profissional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacienteespecialidade',
            name='tipo_atendimento',
        ),
        migrations.AddField(
            model_name='pacienteespecialidade',
            name='procedimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='especialidades.procedimentosespecialidade', verbose_name='Procedimento'),
        ),
    ]
