# Generated by Django 5.2.5 on 2025-09-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0004_alter_pacienteespecialidade_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentoespecialidade',
            name='alterado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alterado por '),
        ),
        migrations.AddField(
            model_name='atendimentoespecialidade',
            name='criado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Criado por '),
        ),
    ]
