# Generated by Django 4.2.7 on 2025-06-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0004_rename_atedimentopaciente_atendimentopaciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimentopaciente',
            old_name='Especialidade',
            new_name='especialidade',
        ),
    ]
