# Generated by Django 4.2.7 on 2025-07-17 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0004_remove_pacienteespecialidade_tipo_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteespecialidade',
            name='procedimento',
            field=models.ForeignKey(default='Consulta', null=True, on_delete=django.db.models.deletion.PROTECT, to='especialidades.procedimentosespecialidade', verbose_name='Procedimento'),
        ),
    ]
