# Generated by Django 4.2.1 on 2023-05-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0004_rename_classficacao_especialidade_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='classificacao',
            field=models.CharField(choices=[('1', 'NORMAL'), ('2', 'URGÊNCIA')], help_text='TIPO DE URGENCIA', max_length=1, verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO')], default=1, max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='tipo_atendimento',
            field=models.CharField(choices=[('1', 'CONSULTA'), ('2', 'RETORNO')], max_length=1, verbose_name='Tipo de Atendimento'),
        ),
    ]
