# Generated by Django 4.2.7 on 2025-06-17 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0005_rename_especialidade_atendimentopaciente_especialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('local_atendimento', models.CharField(choices=[('1', 'CIMBAJE'), ('2', 'CEAE'), ('3', 'RECURSO PRÓPRIO'), ('4', 'SUS')], max_length=1, verbose_name='Tipo de Atendimento')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.especialidade', verbose_name='Especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteSia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendimento_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atend_paciente_especialidade', to='especialidades.atendimentoespecialidade')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.pacienteespecialidade', verbose_name='Especialidade')),
            ],
        ),
        migrations.DeleteModel(
            name='AtendimentoPaciente',
        ),
    ]
