# Generated by Django 5.2.5 on 2025-09-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0005_atendimentoespecialidade_alterado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientesia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente_sia_paciente_especialidade', to='especialidades.pacienteespecialidade', verbose_name='Paciente'),
        ),
    ]
