# Generated by Django 4.2.1 on 2023-05-18 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0005_alter_especialidade_classificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='especialidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='especialidades.tipoespecialidade'),
            preserve_default=False,
        ),
    ]
