# Generated by Django 4.2.6 on 2023-10-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0005_rename_atendespecialidade_atendpaciente_atendespecialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendpaciente',
            name='pacientespecialidade',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Paciente'),
        ),
    ]
