# Generated by Django 4.2.7 on 2025-07-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0006_alter_pacienteespecialidade_procedimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome'),
        ),
    ]
