# Generated by Django 4.2.7 on 2025-06-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0006_atendimentoespecialidade_pacientesia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentoespecialidade',
            name='atendimento_via',
            field=models.CharField(choices=[('1', 'CIMBAJE'), ('2', 'CEAE'), ('3', 'RECURSO PRÓPRIO'), ('4', 'SUS')], default=2, max_length=1, verbose_name=' ATENDIMENTO VIA'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='local_atendimento',
            field=models.CharField(max_length=255, verbose_name='LOCAL DE ATENDIMENTO'),
        ),
    ]
