# Generated by Django 4.2.1 on 2023-05-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0006_alter_especialidade_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoespecialidade_especialidade', to='especialidades.tipoespecialidade'),
        ),
    ]
