# Generated by Django 5.2.5 on 2025-09-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0006_alter_pacientesia_paciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientesia',
            options={'ordering': ['paciente']},
        ),
    ]
