# Generated by Django 4.2.6 on 2023-10-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0006_alter_atendpaciente_pacientespecialidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendpaciente',
            old_name='atendespecialidade',
            new_name='atendimentoespecialidade',
        ),
    ]
