# Generated by Django 4.2.7 on 2025-07-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0007_alter_especialidade_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacienteespecialidade',
            options={},
        ),
    ]
