# Generated by Django 4.2.7 on 2025-06-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0007_atendimentoespecialidade_atendimento_via_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.especialidade', verbose_name='Especialidade2'),
        ),
    ]
