# Generated by Django 5.2.5 on 2025-09-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0007_alter_pacientesia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimentosespecialidade',
            options={'ordering': ['nome_procedimento']},
        ),
    ]
