# Generated by Django 4.2.7 on 2023-11-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0007_rename_atendespecialidade_atendpaciente_atendimentoespecialidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendpaciente',
            name='atendimentoespecialidade',
        ),
        migrations.DeleteModel(
            name='AtendimentoEspecialidade',
        ),
        migrations.DeleteModel(
            name='AtendPaciente',
        ),
    ]
