# Generated by Django 4.2.1 on 2023-05-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0007_alter_especialidade_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='tipo_atendimento',
            field=models.CharField(choices=[('1', 'CONSULTA'), ('2', 'RETORNO'), ('3', 'AVALIAÇÃO')], max_length=1, verbose_name='Tipo de Atendimento'),
        ),
    ]
