# Generated by Django 4.2.7 on 2025-07-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0008_alter_pacienteespecialidade_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientesia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.pacienteespecialidade', verbose_name='Paciente'),
        ),
    ]
