# Generated by Django 4.2.7 on 2023-11-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0003_delete_endereco'),
        ('especialidades', '0008_remove_atendpaciente_atendimentoespecialidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteespecialidade',
            name='profissional',
            field=models.ForeignKey(help_text='ACS', null=True, on_delete=django.db.models.deletion.PROTECT, to='profissionais.profissional', verbose_name='ACS'),
        ),
    ]
