# Generated by Django 5.2.5 on 2025-09-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0008_alter_procedimentosespecialidade_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientesia',
            options={'ordering': ['paciente__procedimento__nome_procedimento']},
        ),
    ]
