# Generated by Django 4.2.7 on 2025-06-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0008_alter_atendimentoespecialidade_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentoespecialidade',
            name='hora_atendimento',
            field=models.DateTimeField(null=True, verbose_name='Horario do Atendimento'),
        ),
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.especialidade', verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='pacientesia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.pacienteespecialidade', verbose_name='Paciente'),
        ),
    ]
