# Generated by Django 4.2.7 on 2025-06-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0009_atendimentoespecialidade_hora_atendimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentoespecialidade',
            name='data',
        ),
        migrations.RemoveField(
            model_name='atendimentoespecialidade',
            name='hora_atendimento',
        ),
        migrations.AddField(
            model_name='atendimentoespecialidade',
            name='data_hora_atendimento',
            field=models.DateTimeField(null=True, verbose_name='Data/Hora'),
        ),
    ]
