# Generated by Django 4.2.7 on 2023-12-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0009_alter_pacienteespecialidade_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(error_messages='Especialidade já cadastrado', max_length=255, unique=True, verbose_name='Nome da Especialidade'),
        ),
    ]
