# Generated by Django 4.2.7 on 2025-07-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0009_alter_pacientesia_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientesia',
            name='procedimento',
        ),
    ]
