# Generated by Django 5.2.5 on 2025-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0009_alter_pacientesia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientesia',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'AUSENTE')], max_length=1, null=True, verbose_name='Status'),
        ),
    ]
