# Generated by Django 5.2.5 on 2025-09-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0010_pacientesia_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientesia',
            options={'ordering': ['paciente__paciente__nome_completo']},
        ),
    ]
