# Generated by Django 4.2.7 on 2025-06-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0010_remove_atendimentoespecialidade_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='atendimento_via',
            field=models.CharField(choices=[('1', 'CIMBAJE'), ('2', 'CEAE'), ('3', 'RECURSO PRÓPRIO'), ('4', 'SUS')], max_length=1, verbose_name=' Atendimento VIA'),
        ),
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='local_atendimento',
            field=models.CharField(max_length=255, verbose_name='Local do Atendimento'),
        ),
    ]
