# Generated by Django 4.2.7 on 2025-08-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0010_remove_pacientesia_procedimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacienteespecialidade',
            options={'ordering': ['-procedimento']},
        ),
        migrations.AlterModelOptions(
            name='pacientesia',
            options={'ordering': ['-paciente']},
        ),
        migrations.AlterModelOptions(
            name='procedimentosespecialidade',
            options={'ordering': ['-nome_procedimento']},
        ),
    ]
