# Generated by Django 4.2.7 on 2023-12-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0010_alter_especialidade_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome da Especialidade'),
        ),
    ]
