# Generated by Django 4.2.7 on 2025-06-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0011_alter_atendimentoespecialidade_atendimento_via_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentoespecialidade',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
