# Generated by Django 4.2.7 on 2025-08-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0011_alter_pacienteespecialidade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentoespecialidade',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO'), ('3', 'CANCELADO')], default=1, max_length=1, null=True, verbose_name='Status'),
        ),
    ]
