# Generated by Django 5.2.5 on 2025-09-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0011_alter_pacientesia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='tipo',
            field=models.CharField(choices=[('1', 'Especialidade'), ('2', 'Procedimento')], max_length=1, null=True, verbose_name='Tipo'),
        ),
    ]
