# Generated by Django 4.2.7 on 2025-06-19 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0004_alter_cidadao_cpf'),
        ('especialidades', '0012_atendimentoespecialidade_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentosEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_procedimento', models.CharField(max_length=255, null=True, verbose_name='Procedimento')),
            ],
        ),
        migrations.AddField(
            model_name='atendimentoespecialidade',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='hora'),
        ),
        migrations.AlterField(
            model_name='pacientesia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidadao.cidadao', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='pacientesia',
            name='procedimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='especialidades.procedimentosespecialidade', verbose_name='Paciente'),
            preserve_default=False,
        ),
    ]
