# Generated by Django 5.2.5 on 2025-09-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0012_especialidade_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='tipo',
            field=models.CharField(choices=[('1', 'ESPECIALIDADE'), ('2', 'PROCEDIMENTO')], max_length=1, null=True, verbose_name='Tipo'),
        ),
    ]
