# Generated by Django 5.2.5 on 2025-08-10 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0011_alter_cidadao_cns_alter_endereco_bairro_and_more'),
        ('especialidades', '0012_atendimentoespecialidade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteespecialidade',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente_especialidade', to='especialidades.especialidade'),
        ),
        migrations.AlterField(
            model_name='pacienteespecialidade',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidadao_especialidade', to='cidadao.cidadao', verbose_name='Paciente'),
        ),
    ]
