# Generated by Django 5.2.5 on 2025-09-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0013_alter_especialidade_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimentoespecialidade',
            options={'ordering': ['data']},
        ),
    ]
