# Generated by Django 5.2.5 on 2025-08-10 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0013_alter_pacienteespecialidade_especialidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteespecialidade',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente_especialidades', to='especialidades.especialidade'),
        ),
    ]
