# Generated by Django 4.2.7 on 2025-06-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0013_procedimentosespecialidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentoespecialidade',
            name='data_hora_atendimento',
        ),
        migrations.AddField(
            model_name='atendimentoespecialidade',
            name='data',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='atendimento_via',
            field=models.CharField(choices=[('1', 'CIMBAJE'), ('2', 'CEAE'), ('3', 'RECURSO PRÓPRIO'), ('4', 'SUS')], max_length=1, verbose_name=' Atendimento Via'),
        ),
        migrations.AlterField(
            model_name='pacientesia',
            name='procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.procedimentosespecialidade', verbose_name='Procedimento'),
        ),
    ]
