# Generated by Django 5.2.5 on 2025-08-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0014_alter_pacienteespecialidade_especialidade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pacientesia',
            unique_together={('atendimento_paciente', 'paciente')},
        ),
    ]
