# Generated by Django 5.2.5 on 2025-09-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0014_alter_atendimentoespecialidade_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientesia',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'AUSENTE'), ('2', 'CONCLUIDO')], help_text='Somente usa quando paciente faltou no atendimento', max_length=1, null=True, verbose_name='Status'),
        ),
    ]
