# Generated by Django 4.2.7 on 2025-06-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0014_remove_atendimentoespecialidade_data_hora_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentoespecialidade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimentoespecialidade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
