# Generated by Django 5.2.5 on 2025-08-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0015_alter_pacientesia_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pacientesia',
            unique_together=set(),
        ),
    ]
