# Generated by Django 4.2.7 on 2025-06-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0015_atendimentoespecialidade_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientesia',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='data',
            field=models.DateField(null=True, verbose_name='Data do Atendimento'),
        ),
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario do Atendimento'),
        ),
    ]
