# Generated by Django 5.2.5 on 2025-09-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0015_alter_pacientesia_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pacientesia',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pacientesia',
            constraint=models.UniqueConstraint(fields=('atendimento_paciente', 'paciente'), name='unique_atendimento_paciente', violation_error_message='Este paciente já está vinculado a este atendimento.'),
        ),
    ]
