# Generated by Django 4.2.7 on 2025-06-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0016_pacientesia_hora_alter_atendimentoespecialidade_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='hora',
            field=models.TimeField(null=True, verbose_name='Horario do Atendimento'),
        ),
    ]
