# Generated by Django 5.2.5 on 2025-09-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0016_alter_pacientesia_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pacientesia',
            name='unique_atendimento_paciente',
        ),
        migrations.AlterUniqueTogether(
            name='pacientesia',
            unique_together={('atendimento_paciente', 'paciente')},
        ),
    ]
