# Generated by Django 5.2.5 on 2025-08-14 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0016_alter_pacientesia_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pacientesia',
            unique_together={('atendimento_paciente', 'paciente')},
        ),
    ]
