# Generated by Django 4.2.7 on 2025-06-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0017_alter_atendimentoespecialidade_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='hora',
            field=models.TimeField(null=True, verbose_name='Horário do Atendimento'),
        ),
        migrations.AlterField(
            model_name='pacientesia',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
    ]
