# Generated by Django 5.2.5 on 2025-08-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0017_alter_pacientesia_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO'), ('3', 'CANCELADO'), ('4', 'AUSENTE')], default=1, max_length=1, null=True, verbose_name='Status'),
        ),
    ]
