# Generated by Django 5.2.5 on 2025-10-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0017_remove_pacientesia_unique_atendimento_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='limite_paciente',
            field=models.IntegerField(default=0, help_text='Limite de pacientes', null=True, verbose_name='Limite de Pacientes'),
        ),
    ]
