# Generated by Django 5.2.5 on 2025-08-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0018_alter_atendimentoespecialidade_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacienteespecialidade',
            options={'ordering': ['-paciente__nome_completo']},
        ),
        migrations.AlterField(
            model_name='atendimentoespecialidade',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO'), ('3', 'CANCELADO')], default=1, max_length=1, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pacienteespecialidade',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO'), ('3', 'CANCELADO'), ('4', 'AUSENTE')], default=1, max_length=1, verbose_name='Status'),
        ),
    ]
