# Generated by Django 4.2.7 on 2025-06-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0018_alter_atendimentoespecialidade_hora_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidade',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='pacienteespecialidade',
            options={'ordering': ['-paciente']},
        ),
    ]
