# Generated by Django 5.2.5 on 2025-10-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0018_especialidade_limite_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidade',
            old_name='limite_paciente',
            new_name='limite_pacientes',
        ),
    ]
