# Generated by Django 5.2.5 on 2025-11-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0019_rename_limite_paciente_especialidade_limite_pacientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientesia',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'AUSENTE'), ('2', 'PRESENTE'), ('3', 'ALTA')], help_text='Somente usa quando paciente faltou no atendimento', max_length=1, null=True, verbose_name='Status'),
        ),
    ]
