# Generated by Django 4.2.7 on 2025-06-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0019_alter_especialidade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientesia',
            options={'ordering': ['paciente']},
        ),
    ]
