# Generated by Django 5.2.5 on 2025-08-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0020_alter_pacienteespecialidade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteespecialidade',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO'), ('3', 'CANCELADO'), ('4', 'AUSENTE'), ('5', 'EM TRATAMENTO'), ('6', 'ALTA')], default=1, max_length=1, verbose_name='Status'),
        ),
    ]
