# Generated by Django 5.2.5 on 2025-08-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0021_alter_pacienteespecialidade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteespecialidade',
            name='alterado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alterado por '),
        ),
        migrations.AddField(
            model_name='pacienteespecialidade',
            name='criado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Criado por '),
        ),
    ]
