# Generated by Django 5.2.5 on 2025-08-25 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0022_pacienteespecialidade_alterado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteespecialidade',
            name='procedimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='especialidades.procedimentosespecialidade', verbose_name='Tipo de Atendimento'),
        ),
    ]
