# Generated by Django 5.2.5 on 2025-08-25 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0023_alter_pacienteespecialidade_procedimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteespecialidade',
            name='procedimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='especialidades.procedimentosespecialidade', verbose_name='Procedimento'),
        ),
    ]
