# Generated by Django 5.2.5 on 2025-09-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0024_alter_pacienteespecialidade_procedimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteespecialidade',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO'), ('3', 'CANCELADO'), ('4', 'AUSENTE'), ('5', 'EM TRATAMENTO'), ('6', 'ALTA'), ('7', 'ACOMPANHAMENTO')], default=1, max_length=1, verbose_name='Status'),
        ),
    ]
