# Generated by Django 4.1.6 on 2023-03-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Estabelecimento')),
                ('cnes', models.PositiveBigIntegerField(unique=True, verbose_name='CNES')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MicroArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microarea', models.PositiveIntegerField(unique=True, verbose_name='Digite Micro-Área')),
            ],
        ),
    ]
