# Generated by Django 4.2.7 on 2025-07-14 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '0001_initial'),
        ('estabelecimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microarea',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profissionais.profissional', verbose_name='Profissional'),
        ),
    ]
