# Generated by Django 4.2.6 on 2023-10-27 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microarea',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estabelecimentos.estabelecimento', verbose_name='Estabelecimento'),
        ),
    ]
