# Generated by Django 4.2.1 on 2023-06-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estabelecimento',
            options={},
        ),
    ]
