# Generated by Django 4.1.6 on 2023-04-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0002_microarea_estabelecimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microarea',
            name='microarea',
            field=models.PositiveIntegerField(unique=True, verbose_name='Micro-Área'),
        ),
    ]
