# Generated by Django 4.2.7 on 2025-06-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0005_remove_profissional_microarea'),
        ('estabelecimentos', '0002_alter_microarea_estabelecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='microarea',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profissionais.profissional', verbose_name='Profisional'),
        ),
    ]
