# Generated by Django 4.1.6 on 2023-04-04 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0003_alter_microarea_microarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microarea',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.estabelecimento', verbose_name='Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='microarea',
            name='microarea',
            field=models.PositiveIntegerField(unique=True, verbose_name='Microárea'),
        ),
    ]
