# Generated by Django 4.2.7 on 2025-06-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0006_profissional_endereco'),
        ('estabelecimentos', '0003_microarea_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microarea',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profissionais.profissional', verbose_name='Profissional'),
        ),
    ]
