# Generated by Django 5.2.5 on 2025-09-03 01:27

import django.db.models.deletion
import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estabelecimentos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('rg', models.CharField(blank=True, max_length=100, null=True, verbose_name='RG')),
                ('cpf', localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('cns', models.PositiveBigIntegerField(help_text='Digite o cartão do SUS com 15 digitos', null=True, unique=True, verbose_name='CNS')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo:')),
                ('dt_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('nome_mae', models.CharField(max_length=150, null=True, verbose_name='Nome da mãe')),
                ('nome_pai', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do  pai')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('telefone1', models.CharField(max_length=15, verbose_name='Celular ')),
                ('raca', models.CharField(choices=[('1', 'AMARELA'), ('2', 'BRANCA'), ('3', 'PARDA'), ('4', 'PRETA'), ('5', 'OUTROS')], max_length=1, null=True, verbose_name='Raça/Cor')),
                ('nacionalidade', models.CharField(max_length=120, null=True, verbose_name='Município de nascimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('microarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='microarea_cidadao', to='estabelecimentos.microarea', verbose_name='Microárea')),
            ],
            options={
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_logradouro', models.CharField(choices=[('1', '---'), ('2', 'RUA'), ('3', 'FAZENDA'), ('4', 'PRACA'), ('5', 'TRAVESSA'), ('6', 'AVENIDA'), ('7', 'SÍTIO')], default='', max_length=1, null=True, verbose_name='CÓD. LOGRADOURO')),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2, verbose_name='UF')),
                ('localizacao', models.CharField(choices=[('1', '---'), ('2', 'Urbana'), ('3', 'Rural')], default='', max_length=1, null=True, verbose_name='Localização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cidadao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_cidadao', to='cidadao.cidadao')),
            ],
            options={
                'ordering': ['logradouro'],
            },
        ),
    ]
