# Generated by Django 4.1.6 on 2023-03-29 09:32

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estabelecimentos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=30)),
                ('complemento', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('rg', models.CharField(blank=True, max_length=10, null=True, verbose_name='RG')),
                ('cpf', localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('cns', models.PositiveIntegerField(help_text='Digite o cartão do SUS com 15 digitos.', unique=True, verbose_name='Cartão do SUS')),
                ('sexo', models.CharField(choices=[('', '----------'), ('F', 'Feminino'), ('M', 'Masculino')], default='', max_length=1, verbose_name='Sexo:')),
                ('dt_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('nome_mae', models.CharField(max_length=150, verbose_name='Nome da Mãe')),
                ('nome_pai', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do  Pai')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('telefone1', models.CharField(max_length=15, unique=True, verbose_name='Celular ')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidadao.endereco')),
                ('microarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='microarea_cidadao', to='estabelecimentos.microarea', verbose_name='Micro Área')),
            ],
        ),
    ]
