# Generated by Django 4.2.1 on 2023-10-21 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0001_initial'),
        ('cidadao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='microarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='microarea_cidadao', to='estabelecimentos.microarea', verbose_name='Micro Área'),
        ),
    ]
