# Generated by Django 4.1.6 on 2023-04-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='cns',
            field=models.PositiveIntegerField(help_text='Digite o cartão do SUS com 15 digitos.', unique=True, verbose_name='CNS'),
        ),
    ]
