# Generated by Django 4.2.7 on 2025-07-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='rg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RG'),
        ),
    ]
