# Generated by Django 4.2.1 on 2023-09-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0002_alter_cidadao_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='localizacao',
            field=models.CharField(choices=[('1', 'URBADO'), ('2', 'RURAL')], max_length=1, null=True, verbose_name='LOCALIZAÇÃO'),
        ),
    ]
