# Generated by Django 4.1.6 on 2023-04-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0002_alter_cidadao_cns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='cns',
            field=models.CharField(help_text='Digite o cartão do SUS com 15 digitos.', max_length=15, unique=True, verbose_name='CNS'),
        ),
    ]
