# Generated by Django 5.2.5 on 2026-03-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0002_enable_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='alterado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alterado por '),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='criado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Criado por '),
        ),
    ]
