# Generated by Django 4.2.1 on 2023-09-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0003_cidadao_localizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidadao',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='endereco',
            name='localizacao',
            field=models.CharField(choices=[('1', 'Urbana'), ('2', 'Rural')], max_length=1, null=True, verbose_name='LOCALIZAÇÃO'),
        ),
    ]
