# Generated by Django 4.2.7 on 2025-07-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0003_alter_endereco_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='raca',
            field=models.CharField(choices=[('1', 'AMARELA'), ('2', 'BRANCO'), ('3', 'PARDA'), ('4', 'PRETO'), ('5', 'OUTROS')], max_length=1, null=True, verbose_name='RAÇA/COR'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='localizacao',
            field=models.CharField(choices=[('1', '---'), ('2', 'Urbana'), ('3', 'Rural')], max_length=1, null=True, verbose_name='LOCALIZAÇÃO'),
        ),
    ]
