# Generated by Django 4.2.7 on 2025-06-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0004_alter_cidadao_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidadao',
            options={'ordering': ['nome_completo']},
        ),
    ]
