# Generated by Django 4.2.7 on 2025-07-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0004_alter_cidadao_raca_alter_endereco_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='telefone1',
            field=models.CharField(max_length=15, verbose_name='Celular '),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='localizacao',
            field=models.CharField(choices=[('1', '---'), ('2', 'Urbana'), ('3', 'Rural')], default='', max_length=1, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
    ]
