# Generated by Django 4.2.1 on 2023-09-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0004_remove_cidadao_localizacao_endereco_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
    ]
