# Generated by Django 4.1.6 on 2023-04-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0004_alter_cidadao_cns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='cns',
            field=models.PositiveBigIntegerField(help_text='Digite o cartão do SUS com 15 digitos, que iniciar  com 7 ou 8.', unique=True, verbose_name='CNS'),
        ),
    ]
