# Generated by Django 4.2.7 on 2025-07-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0005_alter_cidadao_telefone_alter_cidadao_telefone1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['logradouro']},
        ),
    ]
