# Generated by Django 4.2.7 on 2025-06-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0005_alter_cidadao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cod_logradouro',
            field=models.CharField(choices=[('1', 'RUA'), ('2', 'FAZENDA'), ('3', 'PRACA'), ('4', 'TRAVESSA')], default='', max_length=1, null=True, verbose_name='CÓD. LOGRADOURO'),
        ),
    ]
