# Generated by Django 4.2.7 on 2025-07-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0006_alter_endereco_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='raca',
            field=models.CharField(choices=[('1', 'AMARELA'), ('2', 'BRANCA'), ('3', 'PARDA'), ('4', 'PRETA'), ('5', 'OUTROS')], max_length=1, null=True, verbose_name='RAÇA/COR'),
        ),
    ]
