# Generated by Django 4.2.7 on 2025-06-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0006_endereco_cod_logradouro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='nome_mae',
            field=models.CharField(max_length=150, null=True, verbose_name='Nome da Mãe'),
        ),
    ]
