# Generated by Django 4.2.7 on 2025-06-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0007_alter_cidadao_nome_mae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='telefone1',
            field=models.CharField(max_length=15, verbose_name='Celular '),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cod_logradouro',
            field=models.CharField(choices=[('1', '---'), ('2', 'RUA'), ('3', 'FAZENDA'), ('4', 'PRACA'), ('5', 'TRAVESSA')], default='', max_length=1, null=True, verbose_name='CÓD. LOGRADOURO'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='localizacao',
            field=models.CharField(choices=[('1', '---'), ('2', 'Urbana'), ('3', 'Rural')], default='', max_length=1, null=True, verbose_name='LOCALIZAÇÃO'),
        ),
    ]
