# Generated by Django 4.2.7 on 2025-07-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '__first__'),
        ('cidadao', '0007_alter_cidadao_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='dt_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='microarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='microarea_cidadao', to='estabelecimentos.microarea', verbose_name='Microárea'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='nome_completo',
            field=models.CharField(max_length=150, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='nome_mae',
            field=models.CharField(max_length=150, null=True, verbose_name='Nome da mãe'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do  pai'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='raca',
            field=models.CharField(choices=[('1', 'AMARELA'), ('2', 'BRANCA'), ('3', 'PARDA'), ('4', 'PRETA'), ('5', 'OUTROS')], max_length=1, null=True, verbose_name='Raça/Cor'),
        ),
    ]
