# Generated by Django 4.2.7 on 2025-08-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0008_alter_cidadao_dt_nascimento_alter_cidadao_microarea_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidadao',
            options={},
        ),
    ]
