# Generated by Django 4.2.7 on 2025-07-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0008_alter_cidadao_telefone1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='natulidade',
            field=models.CharField(max_length=120, null=True, verbose_name='NACIONALIDADE'),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='raca',
            field=models.CharField(max_length=1, null=True, verbose_name='RAÇA/COR'),
        ),
    ]
