# Generated by Django 4.2.7 on 2025-07-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0009_cidadao_natulidade_cidadao_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='raca',
            field=models.CharField(choices=[('1', 'AMARELA'), ('2', 'BRANCO'), ('3', 'PARDA'), ('4', 'PRETO')], max_length=1, null=True, verbose_name='RAÇA/COR'),
        ),
    ]
