# Generated by Django 4.2.7 on 2025-08-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0009_alter_cidadao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidadao',
            options={'ordering': ['nome_completo']},
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cod_logradouro',
            field=models.CharField(choices=[('1', '---'), ('2', 'RUA'), ('3', 'FAZENDA'), ('4', 'PRACA'), ('5', 'TRAVESSA'), ('6', 'AVENIDA'), ('7', 'SÍTIO')], default='', max_length=1, null=True, verbose_name='CÓD. LOGRADOURO'),
        ),
    ]
