# Generated by Django 4.2.7 on 2025-08-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0010_alter_cidadao_options_alter_endereco_cod_logradouro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='cns',
            field=models.PositiveBigIntegerField(help_text='Digite o cartão do SUS com 15 digitos', null=True, unique=True, verbose_name='CNS'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=100),
        ),
    ]
