# Generated by Django 4.2.7 on 2025-07-07 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0004_alter_microarea_profissional'),
        ('cidadao', '0010_alter_cidadao_raca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidadao',
            name='natulidade',
        ),
        migrations.AddField(
            model_name='cidadao',
            name='nacionalidade',
            field=models.CharField(max_length=120, null=True, verbose_name='Município de nascimento'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='microarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='microarea_cidadao', to='estabelecimentos.microarea', verbose_name='MICRO ÁREA'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='TELEFONE'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='telefone1',
            field=models.CharField(max_length=15, verbose_name='CELULAR '),
        ),
    ]
