# Generated by Django 4.2.7 on 2025-08-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0011_alter_cidadao_cns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=100),
        ),
    ]
