# Generated by Django 4.2.7 on 2025-07-09 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0011_remove_cidadao_natulidade_cidadao_nacionalidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidadao',
            name='endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='cidadao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cidadao.cidadao'),
        ),
    ]
