# Generated by Django 4.2.7 on 2025-07-09 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0012_remove_cidadao_endereco_endereco_cidadao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cidadao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_cidadao', to='cidadao.cidadao'),
        ),
    ]
