# Generated by Django 5.2.5 on 2025-09-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('', '-----------'), ('1', '1-ACS'), ('2', '2-Coordenador'), ('3', '3-Digitador'), ('4', '4-Recepção'), ('5', '5-Secretario'), ('6', '6-Regulação'), ('7', '7-TFD')], default='', max_length=1, verbose_name='Perfil'),
        ),
    ]
