# Generated by Django 4.2.6 on 2023-10-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='status',
        ),
    ]
