# Generated by Django 4.2.1 on 2023-06-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(max_length=1, null=True, verbose_name='Tipo de Usuario'),
        ),
    ]
