# Generated by Django 4.2.1 on 2023-12-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('1', '1-ACS'), ('2', '2-Coordenação'), ('3', '3-Digitador'), ('4', '4-Recepção'), ('5', '5-Secretario'), ('6', '6-Regulação')], max_length=1, null=True, verbose_name='Tipo de Usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ManyToManyField(to='usuarios.perfilusuario'),
        ),
    ]
