# Generated by Django 4.2.1 on 2023-06-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_cpf_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('1', 'Regulação'), ('2', 'Compras'), ('3', 'Coordenação'), ('4', 'recepção'), ('5', 'ACS'), ('6', 'Digitador')], max_length=1, null=True, verbose_name='Tipo de Usuario'),
        ),
    ]
