# Generated by Django 4.2.7 on 2023-12-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_perfilusuario_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'ordering': ['perfil']},
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(choices=[('1', '1-ACS'), ('2', '2-Coordenador'), ('3', '3-Digitador'), ('4', '4-Recepção'), ('5', '5-Secretario'), ('6', '6-Regulação')], max_length=1, null=True, unique=True, verbose_name='Tipo de perfil'),
        ),
    ]
