# Generated by Django 4.2.1 on 2023-06-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dt_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('1', '1-ACS'), ('2', '2-Compras'), ('3', '3-Coordenação'), ('4', '4-Digitador'), ('5', '5-recepção'), ('6', '6-Regulação')], max_length=1, null=True, verbose_name='Tipo de Usuario'),
        ),
    ]
