# Generated by Django 4.2.7 on 2025-06-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('', '-----------'), ('1', '1-ACS'), ('2', '2-Coordenador'), ('3', '3-Digitador'), ('4', '4-Recepção'), ('5', '5-Secretario'), ('6', '6-Regulação')], default='', max_length=1, verbose_name='Perfil'),
        ),
    ]
