# Generated by Django 4.2.1 on 2023-06-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidadao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, verbose_name='nome do Carro')),
                ('placa', models.CharField(help_text='Sem caracteres especiais(-)', max_length=7, verbose_name='Placa do Carro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viagem', models.DateField(verbose_name='Data da Viagem')),
                ('destino_viagem', models.CharField(max_length=180, verbose_name='Destino')),
                ('horario_saida', models.DateTimeField(verbose_name='Horario de Viagem')),
                ('status', models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO')], default=1, max_length=1, verbose_name='Status da Viagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacientesViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_exame', models.CharField(blank=True, max_length=150, null=True, verbose_name='Local do Exame')),
                ('local_espera', models.CharField(blank=True, max_length=150, null=True, verbose_name='Local de Espera')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acompanhante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viagens_acompanhantes', to='cidadao.cidadao')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens_pacientes', to='cidadao.cidadao')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_viagens', to='transportes.viagem')),
            ],
        ),
    ]
