# Generated by Django 4.2.1 on 2023-09-16 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, verbose_name='Nome do Carro')),
                ('placa', models.CharField(help_text='Sem caracteres especiais(-)', max_length=7, unique=True, verbose_name='Placa do Carro')),
                ('foto', models.ImageField(default='', upload_to='media/carros', verbose_name='Foto do carro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viagem', models.DateField(verbose_name='Data da Viagem')),
                ('destino_viagem', models.CharField(max_length=180, verbose_name='Destino')),
                ('horario_saida', models.TimeField(verbose_name='Horario de Viagem')),
                ('status', models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO')], default=1, max_length=1, verbose_name='Status da Viagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carro_viagens', to='transportes.carro')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profissionais.profissional', verbose_name='Motorista')),
            ],
        ),
        migrations.CreateModel(
            name='PassageiroViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=255, verbose_name='Nome do Paciente')),
                ('acompanhante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Acompanhante')),
                ('local_exame', models.CharField(blank=True, max_length=150, null=True, verbose_name='Local do Exame')),
                ('local_espera', models.CharField(blank=True, max_length=150, null=True, verbose_name='Local de Espera')),
                ('telefone', models.CharField(blank=True, help_text='Sem caracteres especiais', max_length=15, null=True, verbose_name='telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiros_viagens', to='transportes.viagem')),
            ],
        ),
    ]
