# Generated by Django 4.2.7 on 2025-07-02 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidadao', '0008_alter_cidadao_telefone1_and_more'),
        ('profissionais', '0006_profissional_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, verbose_name='Nome do Carro')),
                ('placa', models.CharField(help_text='Sem caracteres especiais(-)', max_length=7, unique=True, verbose_name='Placa do Carro')),
                ('foto', models.ImageField(default='', upload_to='media/carros', verbose_name='Foto do carro')),
                ('tipo_transporte', models.CharField(choices=[('1', 'AMBULÂNCIA'), ('2', 'TRANSPORTE SANITÁRIO')], max_length=1, null=True, verbose_name='Tipo de Transporte')),
                ('cor', models.CharField(max_length=100, null=True, verbose_name='Cor do Carro')),
                ('ano_fabricacao', models.IntegerField(null=True, verbose_name='Ano de Fabricação')),
                ('forma_atend', models.CharField(choices=[('1', 'SERVIÇO PRÓPRIO'), ('2', 'SERVIÇO DO CIS')], max_length=1, null=True, verbose_name='Forma de Atendimento')),
                ('fabricante', models.CharField(max_length=100, null=True, verbose_name='Fabricante')),
                ('qta_passageiro', models.IntegerField(null=True, verbose_name='Qta. Passageiro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viagem', models.DateField(verbose_name='Data da Viagem')),
                ('destino_viagem', models.CharField(max_length=180, verbose_name='Destino')),
                ('horario_saida', models.TimeField(verbose_name='Horário de Viagem')),
                ('status', models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO')], default=1, max_length=1, verbose_name='Status da Viagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carro_viagens', to='transportes.carro')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profissionais.profissional', verbose_name='Motorista')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO,PACIENTE UTILIZOU RECURSOS PROPRIO'), ('3', 'NÃO,PERDEU A CONSULTA'), ('4', 'NÃO, SEM INFORMAÇÃO')], max_length=1, verbose_name='Transporte Atendido')),
                ('dt_atendimento', models.DateField(verbose_name='Data do Atendimento')),
                ('tipo_atend', models.CharField(choices=[('1', 'EVENTUAL'), ('2', 'ROTINEIRO')], max_length=1, verbose_name='Tipo Atendimento')),
                ('acompanhante', models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=1, verbose_name='Tem Acompanhante')),
                ('atend_zona_rural', models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=1, verbose_name='Atend. Zona Rural')),
                ('origem', models.CharField(default='SANTO ANTÔNIO DO JACINTO-MG', max_length=200, verbose_name='Origem')),
                ('destino', models.CharField(default='', max_length=200, verbose_name='Destino')),
                ('dist_percorrida', models.PositiveBigIntegerField(help_text='ida e volta', verbose_name='Distância Percorrida (KM)')),
                ('quant_proced_paciente', models.PositiveBigIntegerField(help_text='Paciente', verbose_name='Quant. Procedimento 08.03.01.012-5')),
                ('quant_proced_acompanhante', models.PositiveBigIntegerField(blank=True, help_text='Acompanhante', null=True, verbose_name='Quant. Procedimento 08.03.01.010-9')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carro_registro_transporte', to='transportes.carro', verbose_name='Carro')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidadao.cidadao', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PassageiroViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acompanhante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Acompanhante')),
                ('local_exame', models.CharField(max_length=150, null=True, verbose_name='Local do Exame')),
                ('local_espera', models.CharField(max_length=150, null=True, verbose_name='Local de Espera')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passageiro_viagem', to='cidadao.cidadao', verbose_name='Passageiro')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiros_viagens', to='transportes.viagem')),
            ],
        ),
    ]
