# Generated by Django 4.2.1 on 2023-06-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientesviagem',
            name='telefone',
            field=models.CharField(blank=True, help_text='Sem caracteres especiais', max_length=11, null=True, verbose_name='telefone'),
        ),
    ]
