# Generated by Django 4.2.7 on 2025-07-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
        ('transportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profissionais.profissional', verbose_name='Motorista'),
        ),
    ]
