# Generated by Django 5.2.5 on 2025-09-09 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0001_initial'),
        ('transportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotransporte',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registro_transporte_paciente', to='cidadao.cidadao', verbose_name='Paciente'),
        ),
    ]
