# Generated by Django 4.2.7 on 2025-07-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passageiroviagem',
            old_name='paciente',
            new_name='paciente2',
        ),
    ]
