# Generated by Django 4.2.1 on 2023-10-09 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0001_initial'),
        ('transportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO,PACIENTE UTILIZOU RECURSOS PROPRIO'), ('3', 'NÃO,PERDEU A CONSULTA'), ('4', 'NÃO, SEM INFORMAÇÃO')], max_length=1, verbose_name='Transporte Atendido')),
                ('dt_atendimento', models.DateField(verbose_name='Data de Atendimento')),
                ('tipo_atend', models.CharField(choices=[('1', 'EVENTUAL'), ('2', 'ROTINEIRO')], max_length=1, verbose_name='Tipo Atendimento')),
                ('acompanhante', models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=1, verbose_name='Tem Acompanhante')),
                ('atend_zona_rural', models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=1, verbose_name='Atend. Zona Rural')),
                ('origem', models.CharField(default='SANTO ANTÔNIO DO JACINTO-MG', max_length=200, verbose_name='Origem')),
                ('dist_percorrida', models.PositiveBigIntegerField(verbose_name='Distância Percorrida')),
                ('Quant_proced_paciente', models.PositiveBigIntegerField(verbose_name='Quantidade Procedimento 08.03.01.012-5')),
                ('Quant_proced_acompanhante', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Quantidade Procedimento 08.03.01.010-9')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidadao.cidadao', verbose_name='Paciente')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carro_registro_transporte', to='transportes.carro', verbose_name='Carro')),
            ],
        ),
    ]
