# Generated by Django 5.2.5 on 2025-09-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0002_alter_registrotransporte_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
