# Generated by Django 4.2.7 on 2025-07-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0002_alter_viagem_motorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='status',
            field=models.CharField(choices=[('1', 'ATIVO'), ('2', 'DESATIVADO')], default='1', max_length=1, verbose_name='Status'),
        ),
    ]
