# Generated by Django 4.2.1 on 2023-10-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0002_registrotransporte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrotransporte',
            old_name='placa',
            new_name='carro',
        ),
    ]
