# Generated by Django 4.2.7 on 2025-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0003_carro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotransporte',
            name='acompanhante',
            field=models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=1, verbose_name='Tem acompanhante'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='atend_zona_rural',
            field=models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=1, verbose_name='Atend. Zona rural'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='dist_percorrida',
            field=models.PositiveBigIntegerField(help_text='ida e volta', verbose_name='Distância percorrida (KM)'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='dt_atendimento',
            field=models.DateField(verbose_name='Data do atendimento'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='quant_proced_acompanhante',
            field=models.PositiveBigIntegerField(blank=True, help_text='Acompanhante', null=True, verbose_name='Quant. procedimento 08.03.01.010-9'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='quant_proced_paciente',
            field=models.PositiveBigIntegerField(help_text='Paciente', verbose_name='Quant. procedimento 08.03.01.012-5'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='status',
            field=models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO,PACIENTE UTILIZOU RECURSOS PROPRIO'), ('3', 'NÃO,PERDEU A CONSULTA'), ('4', 'NÃO, SEM INFORMAÇÃO')], max_length=1, verbose_name='Transporte atendido'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='tipo_atend',
            field=models.CharField(choices=[('1', 'EVENTUAL'), ('2', 'ROTINEIRO')], max_length=1, verbose_name='Tipo atendimento'),
        ),
    ]
