# Generated by Django 4.2.1 on 2023-06-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0001_initial'),
        ('profissionais', '0002_alter_profissional_cargo'),
        ('transportes', '0003_viagem_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageiroViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_exame', models.CharField(blank=True, max_length=150, null=True, verbose_name='Local do Exame')),
                ('local_espera', models.CharField(blank=True, max_length=150, null=True, verbose_name='Local de Espera')),
                ('telefone', models.CharField(blank=True, help_text='Sem caracteres especiais', max_length=11, null=True, verbose_name='telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acompanhante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acompanhantes_viagens', to='cidadao.cidadao')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_viagens', to='cidadao.cidadao')),
            ],
        ),
        migrations.AddField(
            model_name='viagem',
            name='motorista',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='profissionais.profissional', verbose_name='Motorista'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PacientesViagem',
        ),
        migrations.AddField(
            model_name='passageiroviagem',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiros_viagens', to='transportes.viagem'),
        ),
    ]
