# Generated by Django 4.2.1 on 2023-10-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0003_rename_placa_registrotransporte_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotransporte',
            name='destino',
            field=models.CharField(max_length=200, null=True, verbose_name='Destino'),
        ),
    ]
