# Generated by Django 5.2.5 on 2025-09-19 20:48

import django.core.validators
import transportes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0003_viagem_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='foto',
            field=models.ImageField(upload_to=transportes.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Foto do carro'),
        ),
    ]
