# Generated by Django 5.2.5 on 2025-10-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0004_alter_carro_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, null=True, verbose_name='Nome do Destino da Viagem')),
            ],
        ),
    ]
