# Generated by Django 4.2.1 on 2023-10-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0004_registrotransporte_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotransporte',
            name='destino',
            field=models.CharField(default='', max_length=200, verbose_name='Destino'),
        ),
    ]
