# Generated by Django 5.2.5 on 2025-08-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0004_alter_registrotransporte_acompanhante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO'), ('3', 'CANCELADO')], default=1, max_length=1, verbose_name='Status da Viagem'),
        ),
    ]
