# Generated by Django 5.2.5 on 2025-08-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0005_alter_viagem_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passageiroviagem',
            options={'ordering': ['-paciente__nome_completo']},
        ),
    ]
