# Generated by Django 4.2.1 on 2023-06-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0005_alter_passageiroviagem_acompanhante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='horario_saida',
            field=models.TimeField(verbose_name='Horario de Viagem'),
        ),
    ]
