# Generated by Django 5.2.5 on 2025-10-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0005_destinoviagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinoviagem',
            options={'ordering': ['nome']},
        ),
    ]
