# Generated by Django 4.2.1 on 2023-06-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0006_alter_viagem_horario_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passageiroviagem',
            name='telefone',
            field=models.CharField(blank=True, help_text='Sem caracteres especiais', max_length=15, null=True, verbose_name='telefone'),
        ),
    ]
