# Generated by Django 5.2.5 on 2025-08-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0006_alter_passageiroviagem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passageiroviagem',
            options={'ordering': ['paciente__nome_completo']},
        ),
    ]
