# Generated by Django 4.2.1 on 2023-06-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0007_alter_passageiroviagem_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(help_text='Sem caracteres especiais(-)', max_length=7, unique=True, verbose_name='Placa do Carro'),
        ),
    ]
