# Generated by Django 4.2.1 on 2023-10-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0007_alter_registrotransporte_quant_proced_acompanhante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotransporte',
            name='quant_proced_acompanhante',
            field=models.PositiveBigIntegerField(blank=True, help_text='Acompanhante', null=True, verbose_name='Qta. Procedimento 08.03.01.010-9'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='quant_proced_paciente',
            field=models.PositiveBigIntegerField(help_text='Paciente', verbose_name='Qta. Procedimento 08.03.01.012-5'),
        ),
    ]
