# Generated by Django 5.2.5 on 2025-08-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0007_alter_passageiroviagem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='alterado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alterado por '),
        ),
        migrations.AddField(
            model_name='viagem',
            name='criado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Criado por '),
        ),
    ]
