# Generated by Django 5.2.5 on 2025-10-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0008_adicionando_destino_viagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='destino_viagem',
        ),
    ]
