# Generated by Django 4.2.1 on 2023-09-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0008_alter_carro_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='foto',
            field=models.ImageField(default='', upload_to='media/carros', verbose_name='Foto do carro'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='nome',
            field=models.CharField(max_length=180, verbose_name='Nome do Carro'),
        ),
    ]
