# Generated by Django 4.2.1 on 2023-10-12 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0008_alter_registrotransporte_quant_proced_acompanhante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotransporte',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 12, 13, 10, 46, 162205, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrotransporte',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
