# Generated by Django 4.2.1 on 2023-10-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0009_registrotransporte_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='ano_fabricacao',
            field=models.IntegerField(null=True, verbose_name='Ano de Fabricacao'),
        ),
        migrations.AddField(
            model_name='carro',
            name='fabricante',
            field=models.CharField(max_length=100, null=True, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='carro',
            name='forma_atend',
            field=models.CharField(choices=[('1', 'SERVIÇO PRÓPRIO'), ('2', 'SERVIÇO DO CIS')], max_length=1, null=True, verbose_name='Forma de Atendimento'),
        ),
        migrations.AddField(
            model_name='carro',
            name='tipo_transporte',
            field=models.CharField(choices=[('1', 'AMBULÂNCIA'), ('2', 'TRANSPORTE SANITÁRIO')], max_length=1, null=True, verbose_name='Tipo de Transporte'),
        ),
    ]
