# Generated by Django 5.2.5 on 2025-10-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0009_remove_viagem_destino_viagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viagem',
            old_name='destino',
            new_name='destino_viagem',
        ),
    ]
