# Generated by Django 5.2.5 on 2025-10-27 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0010_rename_destino_viagem_destino_viagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotransporte',
            name='destino_viagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transportes.destinoviagem', verbose_name='Destino da Viagem'),
        ),
    ]
