# Generated by Django 4.2.1 on 2023-10-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0010_carro_ano_fabricacao_carro_fabricante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotransporte',
            name='dist_percorrida',
            field=models.PositiveBigIntegerField(help_text='ida e volta', verbose_name='Distância Percorrida (KM)'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='quant_proced_acompanhante',
            field=models.PositiveBigIntegerField(blank=True, help_text='Acompanhante', null=True, verbose_name='Quant. Procedimento 08.03.01.010-9'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='quant_proced_paciente',
            field=models.PositiveBigIntegerField(help_text='Paciente', verbose_name='Quant. Procedimento 08.03.01.012-5'),
        ),
    ]
