# Generated by Django 4.2.7 on 2023-12-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0011_alter_registrotransporte_dist_percorrida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotransporte',
            name='dt_atendimento',
            field=models.DateField(verbose_name='Data do Atendimento'),
        ),
    ]
