# Generated by Django 5.2.5 on 2025-10-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0012_adicionando_destino_viagem_registro_transporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrotransporte',
            name='destino',
        ),
    ]
