# Generated by Django 4.2.7 on 2024-01-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0012_alter_registrotransporte_dt_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='cor',
            field=models.CharField(max_length=100, null=True, verbose_name='Cor do Carro'),
        ),
    ]
