# Generated by Django 4.2.7 on 2025-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0013_carro_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passageiroviagem',
            name='local_espera',
            field=models.CharField(max_length=150, null=True, verbose_name='Local de Espera'),
        ),
        migrations.AlterField(
            model_name='passageiroviagem',
            name='local_exame',
            field=models.CharField(max_length=150, null=True, verbose_name='Local do Exame'),
        ),
        migrations.AlterField(
            model_name='passageiroviagem',
            name='telefone',
            field=models.CharField(help_text='Sem caracteres especiais', max_length=15, null=True, verbose_name='telefone'),
        ),
    ]
