# Generated by Django 5.2.5 on 2025-10-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0013_remove_registrotransporte_destino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrotransporte',
            old_name='destino_viagem',
            new_name='destino',
        ),
    ]
