# Generated by Django 5.2.5 on 2025-10-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0014_rename_destino_viagem_registrotransporte_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoviagem',
            name='nome',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Nome'),
        ),
    ]
