# Generated by Django 4.2.7 on 2025-06-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0014_alter_passageiroviagem_local_espera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='qta_passageiro',
            field=models.IntegerField(null=True, verbose_name='Qta. Passageiro'),
        ),
    ]
