# Generated by Django 5.2.5 on 2025-11-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0015_alter_destinoviagem_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotransporte',
            name='alterado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alterado por '),
        ),
        migrations.AddField(
            model_name='registrotransporte',
            name='criado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Criado por '),
        ),
    ]
