# Generated by Django 4.2.7 on 2025-06-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0015_carro_qta_passageiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano_fabricacao',
            field=models.IntegerField(null=True, verbose_name='Ano de Fabricação'),
        ),
    ]
