# Generated by Django 5.2.5 on 2026-01-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0016_registrotransporte_alterado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinoviagem',
            name='valor_localidade',
            field=models.DecimalField(decimal_places=2, help_text='Campo relacionado para Diária', max_digits=10, null=True, verbose_name='Valor do Destino'),
        ),
    ]
