# Generated by Django 4.2.7 on 2025-06-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0016_alter_carro_ano_fabricacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passageiroviagem',
            name='telefone',
            field=models.CharField(blank=True, help_text='Sem caracteres especiais', max_length=15, null=True, verbose_name='telefone'),
        ),
    ]
