# Generated by Django 5.2.5 on 2026-05-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0017_destinoviagem_valor_localidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotransporte',
            name='acompanhante',
            field=models.CharField(blank=True, choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=1, null=True, verbose_name='Tem acompanhante'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transportes.destinoviagem', verbose_name='Destino da Viagem'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='dist_percorrida',
            field=models.PositiveBigIntegerField(blank=True, help_text='ida e volta', null=True, verbose_name='Distância percorrida (KM)'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='origem',
            field=models.CharField(blank=True, default='SANTO ANTÔNIO DO JACINTO-MG', max_length=200, null=True, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='quant_proced_paciente',
            field=models.PositiveBigIntegerField(blank=True, help_text='Paciente', null=True, verbose_name='Quant. procedimento 08.03.01.012-5'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='tipo_atend',
            field=models.CharField(blank=True, choices=[('1', 'EVENTUAL'), ('2', 'ROTINEIRO')], max_length=1, null=True, verbose_name='Tipo atendimento'),
        ),
    ]
