# Generated by Django 4.2.7 on 2025-06-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0017_alter_passageiroviagem_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='horario_saida',
            field=models.TimeField(verbose_name='Horário de Viagem'),
        ),
    ]
