# Generated by Django 5.2.5 on 2026-05-06 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0018_alter_registrotransporte_acompanhante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotransporte',
            name='acompanhante',
            field=models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=1, null=True, verbose_name='Tem acompanhante'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transportes.destinoviagem', verbose_name='Destino da Viagem'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='origem',
            field=models.CharField(default='SANTO ANTÔNIO DO JACINTO-MG', max_length=200, null=True, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='registrotransporte',
            name='tipo_atend',
            field=models.CharField(choices=[('1', 'EVENTUAL'), ('2', 'ROTINEIRO')], max_length=1, null=True, verbose_name='Tipo atendimento'),
        ),
    ]
