# Generated by Django 4.2.7 on 2025-07-14 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidadao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoSIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nome_proced', models.TextField(verbose_name='Nome do Procedimento')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Unitário')),
                ('valor_contrapartida', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Contra Partida')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total')),
                ('valor_passagem', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor da Passagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReciboTFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio_origem', models.CharField(default='Santo Antônio do Jacinto-MG', max_length=120, verbose_name='Município Origem')),
                ('municipio_destino', models.CharField(max_length=120, verbose_name='Município Destino')),
                ('data', models.DateField(verbose_name='Data')),
                ('grs', models.CharField(default='Pedra Azul-MG', max_length=50, verbose_name='GRS')),
                ('especialidade', models.CharField(max_length=100, verbose_name='Especialidade')),
                ('unid_assistencial', models.CharField(max_length=240, null=True, verbose_name='Unidade Assistencial')),
                ('tem_acompanhante', models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=1, verbose_name='Tem Acompanhante')),
                ('atend_fora_estado', models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=1, null=True, verbose_name='Atendimento fora do estado')),
                ('qta_proced', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Quant. Procedimento')),
                ('valor_passagem', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor da Passagem')),
                ('pagamento_por', models.CharField(choices=[('1', 'PIX'), ('2', 'CONTA')], max_length=1, null=True, verbose_name='PAGAMENTO POR')),
                ('agencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='AGENCIA')),
                ('conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='CONTA')),
                ('pix', models.CharField(blank=True, max_length=50, null=True, verbose_name='PIX')),
                ('status', models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'APROVADO'), ('3', 'REPROVADO')], default='1', max_length=1, verbose_name='Avaliar Recibo Pag. de TFD')),
                ('criado_por', models.CharField(blank=True, max_length=200, null=True, verbose_name='Criado por ')),
                ('aprovado_por', models.CharField(blank=True, max_length=200, null=True, verbose_name='Aprovado por ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acompanhante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cidadao.cidadao', verbose_name='Acompanhante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='cidadao.cidadao')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboPassagemTFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_acompanhante', models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=1, verbose_name='Tem Acompanhante')),
                ('meio_transporte', models.CharField(choices=[('1', '1-TERRESTRE'), ('2', '2-AÉREO'), ('3', '3-OUTROS')], max_length=1, verbose_name='Meio de Transporte')),
                ('quant_passagem_paciente', models.PositiveIntegerField(verbose_name='Qta de Passagem')),
                ('quant_passagem_acompanhante', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Qta  Passagem')),
                ('trecho', models.CharField(max_length=200, verbose_name='Trecho')),
                ('codigo_sia_paciente', models.CharField(default='0803010125', max_length=10, null=True, verbose_name='Código SIA')),
                ('codigo_sia_acompanhante', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código SIA')),
                ('valor_paciente_sia', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('valor_acompanhante_sia', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor')),
                ('data_recibo', models.DateField(null=True, verbose_name='Data')),
                ('criado_por', models.CharField(blank=True, max_length=200, null=True, verbose_name='Criado por ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acompanhante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cidadao.cidadao', verbose_name='Acompanhante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibo_passagem_paciente', to='cidadao.cidadao')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimentoSia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_procedimento', models.PositiveBigIntegerField(verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigosia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimento_codigo', to='tfds.codigosia')),
                ('recibo_tfd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimento_recibo_tfd', to='tfds.recibotfd')),
            ],
        ),
    ]
