# Generated by Django 4.2.1 on 2023-06-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidadao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoSIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código SIA')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Unitário')),
                ('qtd_procedimento', models.PositiveBigIntegerField(verbose_name='Quantidade')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReciboTFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio_origem', models.CharField(default='Santo Antônio do Jacinto-MG', max_length=120, verbose_name='Municipio Origem')),
                ('municipio_destino', models.CharField(max_length=120, verbose_name='Municipio Destino')),
                ('data_criada', models.DateField(auto_now_add=True, help_text='Data de Criação')),
                ('data_editada', models.DateField(auto_now=True, help_text='Data de Edição')),
                ('data', models.DateField(verbose_name='Data')),
                ('grs', models.CharField(default='Pedra Azul-MG', max_length=50, verbose_name='GRS')),
                ('especialidade', models.CharField(max_length=100, verbose_name='Especialidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acompanhante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recibo_acompanhante', to='cidadao.cidadao')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='cidadao.cidadao')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboPassagemTFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meio_transporte', models.CharField(max_length=1, verbose_name='Meio de Transporte')),
                ('qta_passagem', models.PositiveIntegerField(verbose_name='Quantidade de Passagem')),
                ('trecho', models.CharField(max_length=200, verbose_name='Trecho')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acompanhante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recibo_passagem_acompanhante', to='cidadao.cidadao')),
                ('codigosia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tfds.codigosia', verbose_name='Código SIA')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibo_passagem_paciente', to='cidadao.cidadao')),
            ],
        ),
        migrations.AddField(
            model_name='codigosia',
            name='recibo_tfd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibo_codigo', to='tfds.recibotfd'),
        ),
    ]
