# Generated by Django 4.2.7 on 2025-07-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibotfd',
            name='atend_fora_estado',
            field=models.CharField(choices=[('1', ''), ('2', 'NÃO'), ('3', 'SIM')], max_length=1, null=True, verbose_name='Atendimento fora do estado'),
        ),
        migrations.AddField(
            model_name='recibotfd',
            name='qta_proced',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='recibotfd',
            name='valor_passagem',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor da Passagem'),
        ),
    ]
