# Generated by Django 4.2.1 on 2023-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosia',
            name='codigo',
            field=models.BigIntegerField(verbose_name='Código SIA'),
        ),
    ]
