# Generated by Django 4.2.1 on 2023-09-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibopassagemtfd',
            name='quant_passagem_acompanhante',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Qta  Passagem'),
        ),
    ]
