# Generated by Django 4.2.7 on 2025-07-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='trecho',
            field=models.CharField(default='SANTO ANTÔNIO DO JACINTO-MG/BELO HORIZONTE-MG', max_length=200, verbose_name='Trecho'),
        ),
    ]
