# Generated by Django 4.1.6 on 2023-04-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfd',
            name='subtotal',
            field=models.CharField(max_length=100, verbose_name='Subtotal'),
        ),
    ]
