# Generated by Django 5.2.5 on 2025-09-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibotfd',
            name='pg_conta',
            field=models.CharField(choices=[('1', '11522-3'), ('2', '14753-2')], help_text='DADOS DA FONTE DE PAGAMENTO ', max_length=1, null=True, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='pg_fonte',
            field=models.CharField(choices=[('1', '1500-1002'), ('2', '1600-0000')], help_text='DADOS DA FONTE DE PAGAMENTO ', max_length=1, null=True, verbose_name='Fonte'),
        ),
    ]
