# Generated by Django 4.2.7 on 2025-07-14 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0002_alter_atendimentoespecialidade_atendimento_via'),
        ('tfds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibotfd',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.especialidade', verbose_name='Especialidade'),
        ),
    ]
