# Generated by Django 4.1.6 on 2023-04-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0002_alter_tfd_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfd',
            name='codigo_sia',
            field=models.ManyToManyField(related_name='tfd_codigo_tfd', to='tfds.codigotfd'),
        ),
    ]
