# Generated by Django 4.2.7 on 2025-07-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0002_recibotfd_atend_fora_estado_recibotfd_qta_proced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibotfd',
            name='qta_proced',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='valor_passagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor da Passagem'),
        ),
    ]
