# Generated by Django 4.2.1 on 2023-08-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0002_alter_recibopassagemtfd_valor_acompanhante_sia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='valor_acompanhante_sia',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor do acompanhante'),
        ),
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='valor_paciente_sia',
            field=models.FloatField(verbose_name='Valor do paciente'),
        ),
    ]
