# Generated by Django 4.2.1 on 2023-05-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0002_alter_codigosia_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosia',
            name='codigo',
            field=models.CharField(max_length=10, verbose_name='Código SIA'),
        ),
    ]
