# Generated by Django 4.2.1 on 2023-08-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0002_recibopassagemtfd_qta_passagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibopassagemtfd',
            name='qta_passagem',
        ),
    ]
