# Generated by Django 4.2.1 on 2023-09-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0002_remove_codigosia_qtd_procedimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigosia',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='codigosia',
            name='codigo',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
    ]
