# Generated by Django 4.2.7 on 2025-07-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0002_alter_recibopassagemtfd_trecho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibotfd',
            name='conta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CONTA'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='pix',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PIX'),
        ),
    ]
