# Generated by Django 4.2.1 on 2023-08-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0003_alter_recibopassagemtfd_valor_acompanhante_sia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='valor_acompanhante_sia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor do acompanhante'),
        ),
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='valor_paciente_sia',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do paciente'),
        ),
    ]
