# Generated by Django 4.2.7 on 2025-08-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0003_alter_recibotfd_conta_alter_recibotfd_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibotfd',
            name='total_gasto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Gasto'),
        ),
    ]
