# Generated by Django 5.2.5 on 2025-09-07 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0001_initial'),
        ('tfds', '0003_alter_recibotfd_pg_conta_alter_recibotfd_pg_fonte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibotfd',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibo_tfd_paciente', to='cidadao.cidadao'),
        ),
    ]
