# Generated by Django 4.2.1 on 2023-06-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0003_remove_recibopassagemtfd_codigosia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='codigo_sia_acompanhante',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código SIA'),
        ),
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='codigo_sia_paciente',
            field=models.CharField(max_length=10, null=True, verbose_name='Código SIA Paciente'),
        ),
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='valor_acompanhante_sia',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='valor_paciente_sia',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Valor Unitário'),
        ),
    ]
