# Generated by Django 4.1.6 on 2023-04-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0003_tfd_codigo_sia'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigotfd',
            name='valor_total',
            field=models.CharField(default='', max_length=50, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
