# Generated by Django 4.2.1 on 2023-08-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0003_remove_recibopassagemtfd_qta_passagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibopassagemtfd',
            name='qta_passagem',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Qta de Passagem'),
        ),
    ]
