# Generated by Django 4.2.1 on 2023-10-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0004_alter_codigosia_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosia',
            name='valor_contrapartida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Contra Partida'),
        ),
        migrations.AlterField(
            model_name='codigosia',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='codigosia',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Unitário'),
        ),
    ]
