# Generated by Django 4.2.7 on 2025-07-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0004_alter_recibotfd_atend_fora_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigosia',
            name='valor_passagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor da Passagem'),
        ),
    ]
