# Generated by Django 4.1.6 on 2023-04-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0004_codigotfd_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfd',
            name='codigo_sia',
        ),
        migrations.AddField(
            model_name='codigotfd',
            name='codigo_sia',
            field=models.ManyToManyField(related_name='tfd_codigo_tfd', to='tfds.tfd'),
        ),
    ]
