# Generated by Django 4.2.7 on 2025-08-05 14:55

from django.db import migrations,models
def calcular_total_existente(apps, schema_editor):
     ReciboTFD = apps.get_model('tfds', 'ReciboTFD')
     ProcedimentoSia = apps.get_model('tfds', 'ProcedimentoSia')
     CodigoSIA = apps.get_model('tfds', 'CodigoSIA')
     
     for recibo in ReciboTFD.objects.all():
        total =0

       
        for procedimento in recibo.procedimento_recibo_tfd.all():
            if procedimento.recibo_tfd.atend_fora_estado == '1':
                if procedimento.codigosia.codigo in ['0803010125', '0803010109']:
                    total += procedimento.qtd_procedimento * recibo.valor_passagem
                else:
                    total += procedimento.qtd_procedimento * procedimento.codigosia.subtotal
            elif procedimento.recibo_tfd.atend_fora_estado == '2':
                if procedimento.codigosia.codigo in ['0803010125', '0803010109']:
                    total += procedimento.qtd_procedimento * procedimento.codigosia.valor_passagem
                else:
                    total += procedimento.codigosia.subtotal * procedimento.qtd_procedimento

        recibo.total_gasto = total
        recibo.save(update_fields=['total_gasto'])

class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0004_recibotfd_total_gasto'),
    ]

    operations = [
       
        migrations.RunPython(calcular_total_existente),
    
    ]
