# Generated by Django 4.2.1 on 2023-06-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0004_alter_recibopassagemtfd_codigo_sia_acompanhante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='valor_acompanhante_sia',
            field=models.CharField(max_length=30, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='valor_paciente_sia',
            field=models.CharField(max_length=30, null=True, verbose_name='Valor'),
        ),
    ]
