# Generated by Django 5.2.5 on 2025-09-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0004_alter_recibotfd_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibotfd',
            name='alterado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alterado por '),
        ),
    ]
