# Generated by Django 5.2.5 on 2025-08-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0005_auto_20250805_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibopassagemtfd',
            options={'ordering': ['paciente__nome_completo']},
        ),
    ]
