# Generated by Django 4.2.1 on 2023-10-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0005_alter_codigosia_valor_contrapartida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigosia',
            name='valor_total',
        ),
    ]
