# Generated by Django 4.2.1 on 2023-06-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0005_alter_recibopassagemtfd_valor_acompanhante_sia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='valor_acompanhante_sia',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Valor'),
        ),
    ]
