# Generated by Django 4.2.7 on 2025-07-07 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0008_alter_cidadao_telefone1_and_more'),
        ('tfds', '0005_codigosia_valor_passagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibotfd',
            name='acompanhante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cidadao.cidadao', verbose_name='Acompanhante'),
        ),
    ]
