# Generated by Django 4.1.6 on 2023-04-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0005_remove_tfd_codigo_sia_codigotfd_codigo_sia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigotfd',
            name='codigo_sia',
        ),
        migrations.AddField(
            model_name='tfd',
            name='codigo_sia',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tfd_codigo_tfd', to='tfds.codigotfd'),
            preserve_default=False,
        ),
    ]
