# Generated by Django 5.2.5 on 2025-10-27 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0005_recibotfd_alterado_por'),
        ('transportes', '0006_alter_destinoviagem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibotfd',
            name='destino_viagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transportes.destinoviagem', verbose_name='Destino da Viagem'),
        ),
    ]
