# Generated by Django 4.1.6 on 2023-04-08 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0006_remove_codigotfd_codigo_sia_tfd_codigo_sia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfd',
            name='codigo_sia',
        ),
        migrations.AddField(
            model_name='codigotfd',
            name='tfd',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='codigo_tfd_tfd', to='tfds.tfd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codigotfd',
            name='qtd_procedimento',
            field=models.PositiveBigIntegerField(verbose_name='Quant. Procedimento'),
        ),
    ]
