# Generated by Django 4.2.1 on 2023-10-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0006_remove_codigosia_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosia',
            name='valor_contrapartida',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=5, null=True, verbose_name='Contra Partida'),
        ),
    ]
