# Generated by Django 5.2.5 on 2025-09-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0006_alter_recibopassagemtfd_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibotfd',
            name='pg_conta',
            field=models.PositiveBigIntegerField(default=115223, null=True, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='recibotfd',
            name='pg_fonte',
            field=models.PositiveIntegerField(default=15001002, null=True, verbose_name='Fonte'),
        ),
    ]
