# Generated by Django 4.2.7 on 2025-07-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0006_alter_recibotfd_acompanhante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibotfd',
            name='cns',
        ),
        migrations.RemoveField(
            model_name='recibotfd',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='recibotfd',
            name='rg',
        ),
    ]
