# Generated by Django 4.2.1 on 2023-08-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0006_recibopassagemtfd_quanti_passagem_acompanhante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibopassagemtfd',
            name='quanti_passagem_acompanhante',
        ),
    ]
