# Generated by Django 4.2.1 on 2023-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0007_alter_codigosia_valor_contrapartida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosia',
            name='nome_proced',
            field=models.TextField(verbose_name='Nome do Procedimento'),
        ),
    ]
