# Generated by Django 4.2.1 on 2023-08-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0007_remove_recibopassagemtfd_quanti_passagem_acompanhante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibopassagemtfd',
            old_name='qta_passagem_paciente',
            new_name='quant_passagem_paciente',
        ),
        migrations.AddField(
            model_name='recibopassagemtfd',
            name='quant_passagem_acompanhante',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Qta de Passagem'),
        ),
    ]
