# Generated by Django 4.2.7 on 2025-07-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0007_remove_recibotfd_cns_remove_recibotfd_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibotfd',
            name='municipio_destino',
            field=models.CharField(max_length=120, verbose_name='Município Destino'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='municipio_origem',
            field=models.CharField(default='Santo Antônio do Jacinto-MG', max_length=120, verbose_name='Município Origem'),
        ),
    ]
