# Generated by Django 5.2.5 on 2025-10-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0007_adicionando_novo_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibotfd',
            name='municipio_destino',
        ),
    ]
