# Generated by Django 5.2.5 on 2025-09-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0007_recibotfd_pg_conta_recibotfd_pg_fonte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibotfd',
            name='pg_conta',
            field=models.PositiveBigIntegerField(default=115223, help_text='DADOS DA FONTE DE PAGAMENTO ', null=True, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='pg_fonte',
            field=models.PositiveIntegerField(default=15001002, help_text='DADOS DA FONTE DE PAGAMENTO ', null=True, verbose_name='Fonte'),
        ),
    ]
