# Generated by Django 4.1.6 on 2023-04-08 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0007_remove_tfd_codigo_sia_codigotfd_tfd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigotfd',
            name='tfd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfds.tfd'),
        ),
    ]
