# Generated by Django 5.2.5 on 2025-10-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0008_remove_recibotfd_municipio_destino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibotfd',
            old_name='destino_viagem',
            new_name='municipio_destino',
        ),
    ]
