# Generated by Django 5.2.5 on 2025-09-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0008_alter_recibotfd_pg_conta_alter_recibotfd_pg_fonte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibotfd',
            name='pg_conta',
            field=models.CharField(help_text='DADOS DA FONTE DE PAGAMENTO ', max_length=30, null=True, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='pg_fonte',
            field=models.CharField(help_text='DADOS DA FONTE DE PAGAMENTO ', max_length=30, null=True, verbose_name='Fonte'),
        ),
    ]
