# Generated by Django 4.2.1 on 2023-10-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0008_alter_codigosia_nome_proced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosia',
            name='valor_contrapartida',
            field=models.DecimalField(blank=True, decimal_places=2, default='0,00', max_digits=5, null=True, verbose_name='Contra Partida'),
        ),
    ]
