# Generated by Django 4.2.7 on 2025-07-12 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0013_alter_endereco_cidadao'),
        ('tfds', '0008_alter_recibotfd_municipio_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibopassagemtfd',
            name='cns',
        ),
        migrations.RemoveField(
            model_name='recibopassagemtfd',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='recibopassagemtfd',
            name='rg',
        ),
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='acompanhante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cidadao.cidadao', verbose_name='Acompanhante'),
        ),
    ]
