# Generated by Django 4.2.1 on 2023-09-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0008_rename_qta_passagem_paciente_recibopassagemtfd_quant_passagem_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosia',
            name='valor_unitario',
            field=models.CharField(max_length=6, verbose_name='Valor Unitário'),
        ),
    ]
