# Generated by Django 4.1.6 on 2023-04-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0002_alter_cidadao_cns'),
        ('tfds', '0008_alter_codigotfd_tfd'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoSIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(verbose_name='Código SIA')),
                ('valor_unitario', models.CharField(max_length=50, verbose_name='Valor Unitário')),
                ('qtd_procedimento', models.PositiveBigIntegerField(verbose_name='Quant. Procedimento')),
                ('valor_total', models.CharField(max_length=50, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='TFD',
            new_name='ReciboTFD',
        ),
        migrations.DeleteModel(
            name='CodigoTFD',
        ),
        migrations.AddField(
            model_name='codigosia',
            name='recibo_tfd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibo_codigo', to='tfds.recibotfd'),
        ),
    ]
