# Generated by Django 4.1.6 on 2023-04-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0009_codigosia_rename_tfd_recibotfd_delete_codigotfd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibotfd',
            name='subtotal',
        ),
    ]
