# Generated by Django 4.2.1 on 2023-09-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0009_alter_codigosia_valor_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosia',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Unitário'),
        ),
    ]
