# Generated by Django 5.2.5 on 2025-10-28 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0009_rename_destino_viagem_recibotfd_municipio_destino'),
        ('transportes', '0015_alter_destinoviagem_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibotfd',
            name='municipio_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transportes.destinoviagem', verbose_name='Município Destino'),
        ),
    ]
