# Generated by Django 5.2.5 on 2025-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0009_alter_recibotfd_pg_conta_alter_recibotfd_pg_fonte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibotfd',
            name='pg_conta',
            field=models.CharField(choices=[('1', '11522-3')], help_text='DADOS DA FONTE DE PAGAMENTO ', max_length=1, null=True, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='pg_fonte',
            field=models.CharField(choices=[('1', '1500-1002')], help_text='DADOS DA FONTE DE PAGAMENTO ', max_length=1, null=True, verbose_name='Fonte'),
        ),
    ]
