# Generated by Django 5.2.5 on 2025-11-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0010_alter_recibotfd_municipio_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibopassagemtfd',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'CONCLUÍDO'), ('3', 'CANCELADO')], default=1, max_length=1, verbose_name='Status'),
        ),
    ]
