# Generated by Django 4.1.6 on 2023-04-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0010_remove_recibotfd_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosia',
            name='qtd_procedimento',
            field=models.PositiveBigIntegerField(verbose_name='Quantidade'),
        ),
    ]
