# Generated by Django 4.2.1 on 2023-06-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0010_alter_recibopassagemtfd_valor_acompanhante_sia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='codigo_sia_paciente',
            field=models.CharField(max_length=10, null=True, verbose_name='Código SIA'),
        ),
    ]
