# Generated by Django 4.1.6 on 2023-04-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0011_alter_codigosia_qtd_procedimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibotfd',
            name='grs',
            field=models.CharField(default='Pedra Azul-MG', max_length=50, verbose_name='GRS'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='municipio_origem',
            field=models.CharField(default='Santo Antônio do Jacinto-MG', max_length=120, verbose_name='Municipio Origem'),
        ),
    ]
