# Generated by Django 5.2.5 on 2025-11-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0011_recibopassagemtfd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibopassagemtfd',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
