# Generated by Django 4.1.6 on 2023-04-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0012_alter_recibotfd_grs_alter_recibotfd_municipio_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosia',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='codigosia',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Unitário'),
        ),
    ]
