# Generated by Django 4.2.1 on 2023-10-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0012_alter_codigosia_valor_contrapartida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosia',
            name='valor_contrapartida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Contra Partida'),
        ),
        migrations.AlterField(
            model_name='codigosia',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Unitário'),
        ),
    ]
