# Generated by Django 4.2.1 on 2023-10-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0015_registrotransporte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroTransporte',
        ),
    ]
