# Generated by Django 4.2.1 on 2023-10-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0016_delete_registrotransporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigosia',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
    ]
