# Generated by Django 4.2.1 on 2023-10-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0020_alter_procedimentosia_codigosia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='acompanhante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Acompanhante'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='acompanhante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Acompanhante'),
        ),
    ]
