# Generated by Django 4.2.1 on 2023-10-21 12:14

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0021_alter_recibopassagemtfd_acompanhante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibopassagemtfd',
            name='cns',
            field=models.PositiveBigIntegerField(help_text='Digite o cartão do SUS com 15 digitos', null=True, unique=True, verbose_name='CNS'),
        ),
        migrations.AddField(
            model_name='recibopassagemtfd',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='recibopassagemtfd',
            name='rg',
            field=models.CharField(max_length=10, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='recibotfd',
            name='cns',
            field=models.PositiveBigIntegerField(help_text='Digite o cartão do SUS com 15 digitos', null=True, unique=True, verbose_name='CNS'),
        ),
        migrations.AddField(
            model_name='recibotfd',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='recibotfd',
            name='rg',
            field=models.CharField(max_length=10, null=True, verbose_name='RG'),
        ),
    ]
