# Generated by Django 4.2.1 on 2023-10-21 12:16

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0022_recibopassagemtfd_cns_recibopassagemtfd_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='cns',
            field=models.PositiveBigIntegerField(blank=True, help_text='Digite o cartão do SUS com 15 digitos', null=True, unique=True, verbose_name='CNS'),
        ),
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='cpf',
            field=localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='recibopassagemtfd',
            name='rg',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='cns',
            field=models.PositiveBigIntegerField(blank=True, help_text='Digite o cartão do SUS com 15 digitos', null=True, unique=True, verbose_name='CNS'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='cpf',
            field=localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='rg',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RG'),
        ),
    ]
