# Generated by Django 4.2.7 on 2023-12-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0024_alter_recibopassagemtfd_cns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibotfd',
            name='aprovado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Aprovado por '),
        ),
        migrations.AddField(
            model_name='recibotfd',
            name='criado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Criado por '),
        ),
        migrations.AddField(
            model_name='recibotfd',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'APROVADO'), ('3', 'REPROVADO')], default='1', max_length=1, verbose_name='Avaliar Diária'),
        ),
    ]
