# Generated by Django 4.2.7 on 2023-12-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0025_recibotfd_aprovado_por_recibotfd_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibotfd',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'APROVADO'), ('3', 'REPROVADO')], default='1', max_length=1, verbose_name='Avaliar Recibo Pag. TFD'),
        ),
    ]
