# Generated by Django 4.2.7 on 2023-12-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0026_alter_recibotfd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibopassagemtfd',
            name='criado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Criado por '),
        ),
        migrations.AddField(
            model_name='recibopassagemtfd',
            name='tem_acompanhante',
            field=models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], default='2', max_length=1, verbose_name='Tem Acompanhante'),
        ),
        migrations.AddField(
            model_name='recibotfd',
            name='tem_acompanhante',
            field=models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], default='2', max_length=1, verbose_name='Tem Acompanhante'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'APROVADO'), ('3', 'REPROVADO')], default='1', max_length=1, verbose_name='Avaliar Recibo Pag. de TFD'),
        ),
    ]
