# Generated by Django 4.2.7 on 2023-12-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0028_alter_recibopassagemtfd_tem_acompanhante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibotfd',
            name='tem_acompanhante',
            field=models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=1, verbose_name='Tem Acompanhante'),
        ),
    ]
