# Generated by Django 4.2.7 on 2025-06-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0029_alter_recibotfd_tem_acompanhante'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibotfd',
            name='agencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='AGENCIA'),
        ),
        migrations.AddField(
            model_name='recibotfd',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='AGENCIA'),
        ),
        migrations.AddField(
            model_name='recibotfd',
            name='pagamento_por',
            field=models.CharField(choices=[('1', 'PIX'), ('2', 'CONTA')], max_length=1, null=True, verbose_name='PAGAMENTO POR'),
        ),
        migrations.AddField(
            model_name='recibotfd',
            name='pix',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='AGENCIA'),
        ),
    ]
