# Generated by Django 4.2.7 on 2025-06-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfds', '0030_recibotfd_agencia_recibotfd_conta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibotfd',
            name='unid_assistencial',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Unidade Assistencial'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CONTA'),
        ),
        migrations.AlterField(
            model_name='recibotfd',
            name='pix',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PIX'),
        ),
    ]
