# Generated by Django 4.1.6 on 2023-03-29 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, choices=[('1', '1-Hotel/Pousada'), ('2', '2-Refeições e Lanches'), ('3', '3-Estacionamento'), ('4', '4-Passagens'), ('5', '5-Táxi'), ('6', '6-Mototáxi'), ('7', '7-Locação de Veículo'), ('8', '8-Combustivel'), ('9', '9-Outros')], help_text='Selecione uma Despesa', max_length=1, null=True, verbose_name='Descrição')),
                ('data_reembolso', models.DateField(verbose_name='Data')),
                ('movimentacao', models.CharField(blank=True, choices=[('', '--------------'), ('1', '1-Valores Adiantados ao Beneficiário'), ('2', '2-Total Geral das despesas Comprovadas'), ('3', '3-Diferença Apurada: Maior'), ('4', '4-Diferença Apurada: Menor'), ('5', '5-Valor Reembolsado ao Colaborador'), ('6', '6-Valor Dev. pelo Colaborador à Empresa')], default=0, help_text='Selecione um Movimento', max_length=1, null=True, verbose_name='Movimentação')),
                ('valor_mov', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor')),
                ('valor_desp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profissionais.profissional', verbose_name='Profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Diaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_diaria', models.DateField(verbose_name='Data')),
                ('viagem_orig', models.CharField(default='SANTO ANTÔNIO DO JACINTO-MG', max_length=180, verbose_name='Origem da Viagem')),
                ('viagem_dest', models.CharField(max_length=200, verbose_name='Destino da Viagem')),
                ('conta', models.PositiveBigIntegerField(verbose_name='Conta')),
                ('fonte', models.PositiveIntegerField(verbose_name='Fonte')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('tipo_diaria', models.CharField(choices=[('', '---------'), ('1', '1-Integral'), ('2', '2-Meia')], default='', max_length=1, verbose_name='Tipo de Diária')),
                ('qta_diaria', models.PositiveBigIntegerField(verbose_name='Quantidade de diária')),
                ('valor', models.CharField(max_length=50, verbose_name='Valor')),
                ('total', models.CharField(max_length=50, verbose_name='Subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profissionais.profissional')),
            ],
        ),
    ]
