# Generated by Django 5.2.5 on 2025-09-03 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, null=True, verbose_name='Descrição')),
            ],
            options={
                'ordering': ['-descricao'],
            },
        ),
        migrations.CreateModel(
            name='Diaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição ')),
                ('data_diaria', models.DateField(verbose_name='Data')),
                ('reembolso', models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=1, verbose_name='Reembolso')),
                ('viagem_orig', models.CharField(default='SANTO ANTÔNIO DO JACINTO-MG', max_length=180, verbose_name='Origem da Viagem')),
                ('viagem_dest', models.CharField(max_length=200, verbose_name='Destino da Viagem')),
                ('conta', models.PositiveBigIntegerField(default=115223, verbose_name='Conta')),
                ('fonte', models.PositiveIntegerField(default=15001002, verbose_name='Fonte')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('tipo_diaria', models.CharField(choices=[('', '---------'), ('1', 'Integral'), ('2', 'Meia'), ('3', 'Integral+Meia')], default='', max_length=1, verbose_name='Tipo de Diária')),
                ('qta_diaria', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'APROVADO'), ('3', 'REPROVADO')], default='1', max_length=1, verbose_name='Avaliar')),
                ('criado_por', models.CharField(blank=True, max_length=200, null=True, verbose_name='Criado por ')),
                ('aprovado_por', models.CharField(blank=True, max_length=200, null=True, verbose_name='Aprovado por ')),
                ('descricao_reembolso', models.TextField(blank=True, null=True, verbose_name='Descrição Reembolso')),
                ('data_ult_nota_reembolso', models.DateField(help_text='Colocar data última nota', null=True, verbose_name='Data última nota')),
                ('alterado_por', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alterado por ')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profissionais', to='profissionais.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_desp', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor')),
                ('obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='OBSERVAÇÃO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='despesas.descricaoreembolso', verbose_name='Descrição')),
                ('diaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to='despesas.diaria')),
            ],
            options={
                'ordering': ['-descricao'],
            },
        ),
    ]
