# Generated by Django 4.1.6 on 2023-04-13 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reembolso',
            name='profissional',
        ),
        migrations.AddField(
            model_name='reembolso',
            name='diaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reembolso_diaria', to='despesas.diaria'),
            preserve_default=False,
        ),
    ]
