# Generated by Django 5.2.5 on 2025-10-06 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReembolsoPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'APROVADO'), ('3', 'REPROVADO')], default='1', max_length=1, verbose_name='Avaliar')),
                ('criado_por', models.CharField(blank=True, max_length=200, null=True, verbose_name='Criado por ')),
                ('aprovado_por', models.CharField(blank=True, max_length=200, null=True, verbose_name='Aprovado por ')),
                ('descricao_reembolso', models.TextField(blank=True, null=True, verbose_name='Descrição Reembolso')),
                ('data_ult_nota_reembolso', models.DateField(blank=True, help_text='Colocar data última nota', null=True, verbose_name='Data última nota')),
                ('alterado_por', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alterado por ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reembolso_principal', to='despesas.diaria')),
            ],
        ),
    ]
