# Generated by Django 4.2.1 on 2023-08-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
