# Generated by Django 4.2.7 on 2025-07-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_alter_diaria_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
