# Generated by Django 4.2.7 on 2023-11-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_alter_reembolso_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='diaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to='despesas.diaria'),
        ),
    ]
