# Generated by Django 4.2.1 on 2023-08-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_alter_diaria_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='tipo_diaria',
            field=models.CharField(choices=[('', '---------'), ('1', 'Integral'), ('2', 'Meia')], default='', max_length=1, verbose_name='Tipo de Diária'),
        ),
    ]
