# Generated by Django 4.1.6 on 2023-04-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_remove_reembolso_profissional_reembolso_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='valor_desp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='valor_mov',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor'),
        ),
    ]
