# Generated by Django 5.2.5 on 2025-10-06 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_reembolsoprincipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolso',
            name='reembolso_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to='despesas.reembolsoprincipal'),
        ),
    ]
