# Generated by Django 4.1.6 on 2023-04-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_alter_reembolso_valor_desp_alter_reembolso_valor_mov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reembolso',
            name='data_reembolso',
        ),
    ]
