# Generated by Django 4.2.7 on 2025-07-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_alter_diaria_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='conta',
            field=models.PositiveBigIntegerField(default=115223, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='diaria',
            name='fonte',
            field=models.PositiveIntegerField(default=15001002, verbose_name='Fonte'),
        ),
    ]
