# Generated by Django 4.2.7 on 2023-12-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_alter_reembolso_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaria',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'APROVADO'), ('3', 'REPROVADO')], default='1', max_length=1, verbose_name='Status'),
        ),
    ]
