# Generated by Django 4.1.6 on 2023-04-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_remove_reembolso_data_reembolso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='qta_diaria',
            field=models.PositiveBigIntegerField(verbose_name='Quantidade'),
        ),
    ]
