# Generated by Django 4.2.7 on 2025-07-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_alter_diaria_conta_alter_diaria_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolso',
            name='descricao_reembolso',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
