# Generated by Django 5.2.5 on 2025-10-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_auto_20251006_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaria',
            name='data_ult_nota_reembolso',
        ),
        migrations.RemoveField(
            model_name='diaria',
            name='descricao_reembolso',
        ),
        migrations.RemoveField(
            model_name='reembolso',
            name='diaria',
        ),
    ]
