# Generated by Django 4.2.7 on 2023-12-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_diaria_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaria',
            name='aprovado_diaria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diaria',
            name='user_create_diaria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
