# Generated by Django 4.2.7 on 2023-12-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0005_diaria_aprovado_diaria_diaria_user_create_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='aprovado_diaria',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Aprovado por '),
        ),
        migrations.AlterField(
            model_name='diaria',
            name='user_create_diaria',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Criado por '),
        ),
    ]
