# Generated by Django 5.2.5 on 2025-10-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0005_remove_diaria_data_ult_nota_reembolso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descricaoreembolso',
            options={'ordering': ['descricao']},
        ),
    ]
