# Generated by Django 4.1.6 on 2023-04-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0005_alter_diaria_qta_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='descricao',
            field=models.CharField(choices=[('1', '1-Hotel/Pousada'), ('2', '2-Refeições e Lanches'), ('3', '3-Estacionamento'), ('4', '4-Passagens'), ('5', '5-Táxi'), ('6', '6-Mototáxi'), ('7', '7-Locação de Veículo'), ('8', '8-Combustivel'), ('9', '9-Outros')], max_length=1, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='movimentacao',
            field=models.CharField(choices=[('1', '1-Valores Adiantados ao Beneficiário'), ('2', '2-Total Geral das despesas Comprovadas'), ('3', '3-Diferença Apurada: Maior'), ('4', '4-Diferença Apurada: Menor'), ('5', '5-Valor Reembolsado ao Colaborador'), ('6', '6-Valor Dev. pelo Colaborador à Empresa')], default=1, max_length=1, verbose_name='Movimentação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='valor_desp',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='valor_mov',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
