# Generated by Django 4.1.6 on 2023-04-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0006_alter_reembolso_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='descricao',
            field=models.CharField(blank=True, choices=[('1', '1-Hotel/Pousada'), ('2', '2-Refeições e Lanches'), ('3', '3-Estacionamento'), ('4', '4-Passagens'), ('5', '5-Táxi'), ('6', '6-Mototáxi'), ('7', '7-Locação de Veículo'), ('8', '8-Combustivel'), ('9', '9-Outros')], help_text='Selecione uma Despesa', max_length=1, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='movimentacao',
            field=models.CharField(blank=True, choices=[('', '--------------'), ('1', '1-Valores Adiantados ao Beneficiário'), ('2', '2-Total Geral das despesas Comprovadas'), ('3', '3-Diferença Apurada: Maior'), ('4', '4-Diferença Apurada: Menor'), ('5', '5-Valor Reembolsado ao Colaborador'), ('6', '6-Valor Dev. pelo Colaborador à Empresa')], default=0, help_text='Selecione um Movimento', max_length=1, null=True, verbose_name='Movimentação'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='valor_desp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='valor_mov',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor'),
        ),
    ]
