# Generated by Django 4.2.7 on 2025-07-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0006_alter_reembolso_valor_desp_alter_reembolso_valor_mov'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.RemoveField(
            model_name='reembolso',
            name='descricao_reembolso',
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='valor_desp',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='valor_mov',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=8, null=True, verbose_name='Valor'),
        ),
    ]
