# Generated by Django 5.2.5 on 2025-10-26 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0006_alter_descricaoreembolso_options'),
        ('transportes', '0005_destinoviagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaria',
            name='novo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transportes.destinoviagem'),
        ),
    ]
