# Generated by Django 4.2.7 on 2025-07-16 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0007_descricaoreembolso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolso',
            name='descricao_reembolso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='despesas.descricaoreembolso', verbose_name='Descrição do reembolso'),
        ),
    ]
