# Generated by Django 4.2.7 on 2023-12-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0007_alter_diaria_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaria',
            old_name='aprovado_diaria',
            new_name='aprovado_por',
        ),
        migrations.RenameField(
            model_name='diaria',
            old_name='user_create_diaria',
            new_name='criado_por',
        ),
    ]
