# Generated by Django 5.2.5 on 2025-10-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0008_adicionando_novo_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaria',
            name='viagem_dest',
        ),
    ]
