# Generated by Django 4.1.6 on 2023-04-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0008_alter_reembolso_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='movimentacao',
            field=models.CharField(blank=True, choices=[('1', '1-Valores Adiantados ao Beneficiário'), ('2', '2-Total Geral das despesas Comprovadas'), ('3', '3-Diferença Apurada: Maior'), ('4', '4-Diferença Apurada: Menor'), ('5', '5-Valor Reembolsado ao Colaborador'), ('6', '6-Valor Dev. pelo Colaborador à Empresa')], max_length=1, null=True, verbose_name='Movimentação'),
        ),
    ]
