# Generated by Django 4.2.7 on 2025-07-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0009_alter_reembolso_valor_desp_alter_reembolso_valor_mov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reembolso',
            name='descricao_reembolso',
        ),
        migrations.DeleteModel(
            name='DescricaoReembolso',
        ),
    ]
