# Generated by Django 4.1.6 on 2023-04-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0009_alter_reembolso_movimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='valor_desp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='valor_mov',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor'),
        ),
    ]
