# Generated by Django 5.2.5 on 2025-10-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0009_remove_diaria_viagem_dest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaria',
            old_name='novo_destino',
            new_name='viagem_dest',
        ),
    ]
