# Generated by Django 4.2.7 on 2025-07-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0010_remove_reembolso_descricao_reembolso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaria',
            name='descricao_rembolso',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Reembolso'),
        ),
    ]
