# Generated by Django 5.2.5 on 2025-10-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0010_rename_novo_destino_diaria_viagem_dest'),
        ('transportes', '0005_destinoviagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='viagem_dest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transportes.destinoviagem', verbose_name='Destino da Viagem'),
        ),
    ]
