# Generated by Django 4.1.6 on 2023-04-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0010_alter_reembolso_valor_desp_alter_reembolso_valor_mov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='diaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaria', to='despesas.diaria'),
        ),
    ]
