# Generated by Django 5.2.5 on 2025-10-28 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0011_alter_diaria_viagem_dest'),
        ('transportes', '0015_alter_destinoviagem_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='viagem_dest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transportes.destinoviagem', verbose_name='Destino da Viagem'),
        ),
    ]
