# Generated by Django 4.2.7 on 2025-07-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0011_diaria_descricao_rembolso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaria',
            old_name='descricao_rembolso',
            new_name='descricao_reembolso',
        ),
    ]
