# Generated by Django 5.2.5 on 2026-01-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0012_alter_diaria_viagem_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaria',
            name='valor_fixo',
            field=models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], default=1, max_length=1, verbose_name='Valor é fixo'),
        ),
    ]
