# Generated by Django 4.1.6 on 2023-04-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0013_alter_reembolso_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaria',
            name='reembolso',
            field=models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], default='', max_length=1, verbose_name='Vai ter Reembolso ?'),
            preserve_default=False,
        ),
    ]
