# Generated by Django 5.2.5 on 2026-01-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0013_diaria_valor_fixo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da diária'),
        ),
        migrations.AlterField(
            model_name='diaria',
            name='valor_fixo',
            field=models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], default=1, max_length=1, verbose_name='Valor é Fixo'),
        ),
    ]
