# Generated by Django 4.2.7 on 2025-07-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0014_remove_reembolso_movimentacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reembolso',
            name='criado_por',
        ),
    ]
