# Generated by Django 4.1.6 on 2023-04-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0014_diaria_reembolso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='reembolso',
            field=models.CharField(choices=[('1', 'SIM'), ('2', 'NÃO')], max_length=1, verbose_name='Reembolso'),
        ),
    ]
