# Generated by Django 4.1.6 on 2023-04-30 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0014_alter_profissional_cns'),
        ('despesas', '0015_alter_diaria_reembolso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profissionais', to='profissionais.profissional'),
        ),
    ]
