# Generated by Django 4.2.7 on 2025-07-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0015_remove_reembolso_criado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reembolso',
            name='aprovado_por',
        ),
        migrations.RemoveField(
            model_name='reembolso',
            name='status',
        ),
    ]
