# Generated by Django 4.2.7 on 2025-07-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0016_remove_reembolso_aprovado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='status',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'APROVADO'), ('3', 'REPROVADO')], default='1', max_length=1, verbose_name='Avaliar'),
        ),
    ]
