# Generated by Django 4.2.7 on 2025-07-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0017_alter_diaria_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='qta_diaria',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Quantidade'),
        ),
    ]
