# Generated by Django 4.2.7 on 2025-07-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0018_alter_diaria_qta_diaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.AlterField(
            model_name='diaria',
            name='tipo_diaria',
            field=models.CharField(choices=[('', '---------'), ('1', 'Integral'), ('2', 'Meia'), ('3', 'Integral+Meia')], default='', max_length=1, verbose_name='Tipo de Diária'),
        ),
    ]
