# Generated by Django 4.2.7 on 2025-07-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0020_alter_reembolso_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaria',
            name='data_ult_nota_reembolso',
            field=models.DateField(help_text='Colocar data última nota', null=True, verbose_name='Data última nota'),
        ),
    ]
