# Generated by Django 4.2.7 on 2025-07-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0021_diaria_data_ult_nota_reembolso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricaoreembolso',
            name='descricao',
            field=models.CharField(max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
