# Generated by Django 4.2.7 on 2025-08-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0022_alter_descricaoreembolso_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descricaoreembolso',
            options={'ordering': ['-descricao']},
        ),
        migrations.AlterModelOptions(
            name='reembolso',
            options={'ordering': ['-descricao']},
        ),
    ]
