# Generated by Django 5.2.5 on 2025-08-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0023_alter_descricaoreembolso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaria',
            name='alterado_por',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alterado por '),
        ),
    ]
